INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Фомина Эмилия Юльевна', '4041967', 'г. Котельнич, алл. Водников, д. 8/8 к. 8, 067551', '+7 (652) 987-0449', '9121 512949')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Лукия Афанасьевна Михайлова', '8543962', 'клх Екатеринбург, алл. Курганная, д. 9/3 стр. 3, 157752', '8 175 440 25 26', '9216 595327')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Жданов Игорь Филиппович', '2495346', 'к. Россошь, пр. Привокзальный, д. 5/3 стр. 3/8, 085656', '+7 (470) 674-08-79', '8310 887537')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Федотов Поликарп Арсеньевич', '8608698', 'с. Петропавловск-Камчатский, ш. Ореховое, д. 50, 647020', '8 (956) 935-28-45', '6801 849300')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Зыков Бажен Данилович', '7180594', 'д. Соболево, алл. 50 лет Октября, д. 57, 734363', '84069548527', '3414 680445')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Касьян Федосьевич Котов', '2216963', 'к. Сладково, алл. Балтийская, д. 75 стр. 5, 421713', '8 (752) 755-56-90', '1903 223600')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Ангелина Кузьминична Большакова', '4931087', 'клх Долинск, пер. Первомайский, д. 741 к. 7, 995625', '+7 720 677 51 48', '4914 086255')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Панова Евфросиния Андреевна', '9604382', 'д. Выборг, пер. Луговой, д. 17, 810255', '87215159522', '8601 721812')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Анастасия Викторовна Кудряшова', '7173393', 'п. Курумкан, алл. Карла Маркса, д. 849 к. 9/2, 403837', '+70756246726', '3114 718272')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Лора Игоревна Наумова', '6322428', 'г. Смоленск, пр. Геологов, д. 3 к. 19, 379393', '+76665364731', '3919 710365')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Михеева Людмила Михайловна', '8357923', 'к. Семлячики, алл. Ломоносова, д. 72 к. 5/5, 186479', '8 (867) 670-99-78', '2821 150174')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Кира Макаровна Михайлова', '5426468', 'с. Гремячинск (Бурят.), бул. Волгоградский, д. 17 стр. 9, 042264', '8 573 369 61 58', '0305 923536')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Колесникова Клавдия Ильинична', '9798110', 'с. Красноярск, пр. Троицкий, д. 7/3, 079740', '+7 209 061 4218', '4721 458042')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Варвара Егоровна Кулакова', '6557392', 'с. Елец, наб. Кольцова, д. 8/5 стр. 8/8, 042166', '8 911 335 84 01', '4721 827625')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Владлен Дмитриевич Большаков', '7900225', 'клх Красногорск (Моск.), бул. Осенний, д. 699 стр. 107, 441823', '+7 970 867 16 35', '0906 106419')
INSERT INTO Workshop (workshop_name, workshop_dir_name, workshop_addr) VALUES('Цех1', 'Федосеев Осип Егорович', 'п. Оса, пер. Степной, д. 787 стр. 1, 075657')
INSERT INTO Workshop (workshop_name, workshop_dir_name, workshop_addr) VALUES('Цех2', 'Фролов Леонтий Давыдович', 'с. Рыбинск, алл. Высоцкого, д. 5, 335432')
INSERT INTO Workshop (workshop_name, workshop_dir_name, workshop_addr) VALUES('Цех3', 'Ираида Ильинична Волкова', 'клх Пятигорск, пер. Геологов, д. 1 к. 392, 360760')
INSERT INTO Workshop (workshop_name, workshop_dir_name, workshop_addr) VALUES('Цех4', 'Агата Анатольевна Ковалева', 'к. Оренбург, пер. З.Космодемьянской, д. 113 к. 63, 520294')
INSERT INTO Workshop (workshop_name, workshop_dir_name, workshop_addr) VALUES('Цех5', 'Нонна Егоровна Петрова', 'ст. Кызыл, бул. Ленинский, д. 4, 420936')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Никифор Бориславович Носов', '6720918', '+7 (121) 976-93-38', '9121 755496', 'клх Асбест, алл. Кочубея, д. 2/1 стр. 3/9, 272482', '5')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Комиссаров Фрол Фокич', '2625876', '+78969813074', '7501 244069', 'с. Красноуфимск, ш. 40 лет Октября, д. 96 стр. 6/3, 453249', '1')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Беляев Климент Федотович', '2950658', '8 902 884 86 55', '7111 649157', 'клх Внуково (метеост.), пр. Станиславского, д. 776 стр. 8/4, 821976', '4')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Рыбаков Тит Федосьевич', '6250672', '+7 168 735 7573', '0708 686524', 'к. Раменское, ш. Таежное, д. 70, 171094', '2')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Анисимова Ия Геннадиевна', '3017772', '+7 (369) 319-38-74', '8714 070417', 'п. Сусуман, ш. Троицкое, д. 82 к. 57, 494763', '1')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Пелагея Вениаминовна Архипова', '4799609', '+7 (206) 362-0735', '0910 111120', 'г. Холмогоры, наб. Придорожная, д. 14 стр. 382, 776408', '5')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Голубева Александра Эдуардовна', '7249159', '8 (818) 936-2962', '2611 616762', 'п. Чайковский, пер. Клубный, д. 32 к. 6/9, 426334', '3')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Ковалева Варвара Алексеевна', '7241488', '+7 (136) 727-1913', '0216 969108', 'п. Череповец, алл. Вахитова, д. 597 к. 7, 632121', '1')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Валерьян Филатович Белозеров', '8820036', '+7 545 033 53 10', '8507 331664', 'с. Ноглики, пер. Гайдара, д. 694 стр. 5, 473945', '4')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Фролов Натан Филиппович', '3324809', '+79158640494', '8807 138131', 'клх Ардон, наб. Тукая, д. 44 стр. 19, 685691', '1')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Беляков Денис Юлианович', '6552281', '+7 224 960 7539', '7119 249808', 'клх Пышма, пер. Циолковского, д. 2, 660684', '1')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Рябов Натан Харлампьевич', '5024269', '+7 (747) 636-6609', '7916 816377', 'п. Ершов, пер. Парковый, д. 59 стр. 2, 860754', '4')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Фокина Фаина Борисовна', '3136537', '+7 290 173 3768', '0902 672927', 'г. Шелагонцы, ул. Новосельская, д. 7/5, 898957', '2')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Белоусова Елена Дмитриевна', '4505350', '8 386 800 9301', '4002 084956', 'ст. Усть-Камчатск, пр. Крылова, д. 4, 886975', '5')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Глафира Петровна Афанасьева', '8558128', '8 694 880 6037', '8216 484163', 'к. Красноселькуп, пр. Нижний, д. 425 стр. 754, 784718', '4')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Тула, алл. Путевая, д. 274 к. 5/8, 342377', '2420 879918', '2017-07-03', '7')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Северобайкальск, ш. Лесозаводское, д. 661 к. 7/6, 240554', '6905 220414', '2021-07-30', '13')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('клх Егорьевск, ул. Шолохова, д. 5/8, 282405', '0507 070226', '2019-05-03', '8')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('ст. Костомукша, ш. Степана Разина, д. 8 стр. 3/2, 408813', '5605 717416', '2020-03-24', '5')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('с. Хоста, ш. Маркса Карла, д. 4 стр. 4, 724922', '7906 965909', '2019-03-19', '15')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Каменск-Уральский, пр. Карла Маркса, д. 8/9, 304548', '3220 471274', '2021-07-05', '9')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('д. Баргузин, ул. Мирная, д. 569 стр. 44, 990427', '0714 568240', '2020-06-18', '14')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Балашов, ш. Клубное, д. 2 стр. 4/1, 409681', '8212 075398', '2020-12-28', '2')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('с. Томск, ш. Мостовое, д. 9/8 к. 8/3, 805648', '1805 654530', '2018-04-20', '3')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Уфа, ул. Пограничная, д. 207 стр. 1/8, 676583', '6420 877520', '2020-02-02', '10')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Вендинга, алл. Овражная, д. 4, 196296', '9504 625616', '2020-03-04', '15')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Норильск, пр. Николаева, д. 443 к. 64, 452119', '1002 631623', '2020-04-16', '12')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Эльбрус, пр. Прибрежный, д. 95 стр. 254, 298546', '3204 875475', '2018-11-04', '1')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('с. Слюдянка, алл. Ольховая, д. 2 стр. 282, 772802', '2718 800157', '2021-08-03', '6')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('с. Оймякон, наб. 60 лет Октября, д. 65 к. 41, 256614', '1313 849610', '2021-03-31', '1')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Шатой, ш. Красное, д. 74 стр. 78, 657186', '6020 744484', '2020-01-14', '8')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Смоленск, ш. Локомотивное, д. 4 к. 80, 796524', '3604 050699', '2019-12-09', '12')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('п. Кропоткин (Краснод.), алл. Сибирская, д. 2 к. 645, 301051', '2901 326014', '2020-11-19', '8')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('п. Крымск, пр. Осипенко, д. 6 к. 6/4, 831841', '3802 623849', '2021-02-09', '11')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Воткинск, ш. Астраханское, д. 4 стр. 76, 286782', '3106 495313', '2017-07-03', '6')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие1', '10000', 'Reiciendis praesentium rem quos doloremque iste nulla aliquam.', '26')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие2', '2300', 'Ex animi odio tempora. Accusamus fugit ea molestias.', '10')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие3', '3800', 'Distinctio laborum consectetur aperiam. Error adipisci quis quos est.', '5')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие4', '300', 'Nulla repellat eligendi eius rem exercitationem atque explicabo.', '0')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие5', '2100', 'Rerum impedit consectetur blanditiis. Delectus dolorem nesciunt deserunt.', '9')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие6', '2300', 'Veniam nam delectus cum dolore odit laudantium.', '17')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие7', '7400', 'Necessitatibus quos ab provident molestias hic dolorem in.', '7')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие8', '6200', 'Cumque quibusdam accusamus sint voluptatibus repellendus quam. Natus veritatis tempora natus.', '39')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие9', '2900', 'Odit facilis labore. Doloremque repellat quos quidem ratione unde.', '28')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие10', '2100', 'Expedita asperiores ut error illum ex.', '16')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие11', '6000', 'Inventore illum quaerat soluta quae.
Dolorum corrupti optio nihil praesentium vel quisquam.', '49')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие12', '600', 'Deleniti error ea cum tempora. Architecto sequi fugiat.', '23')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие13', '1600', 'Laborum quis dolor impedit quis maiores. Ut dignissimos sint.', '10')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие14', '4300', 'Eligendi error nostrum corrupti delectus. Quibusdam magni temporibus illum dolor numquam.', '34')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие15', '3500', 'Quae voluptatum autem explicabo rem. Quo officiis temporibus dicta.', '30')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие16', '7100', 'Necessitatibus dolorem distinctio saepe quod. Quidem aliquam nisi non officiis.', '11')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие17', '7500', 'Inventore ad nesciunt cupiditate quia omnis velit.', '48')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие18', '800', 'Ab accusamus pariatur repudiandae saepe. Repudiandae nulla nobis minima.', '7')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие19', '1000', 'Id dignissimos quos pariatur nam nam eius. Eius reiciendis itaque sint maiores veritatis.', '11')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие20', '7600', 'Ipsam porro dignissimos impedit. Consequuntur accusantium quisquam officia unde reprehenderit est.', '29')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие21', '8600', 'Nulla iste reiciendis suscipit.', '40')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие22', '600', 'Repellendus voluptatem vero nam quod doloremque ipsa.', '24')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие23', '3800', 'Magni repudiandae facere nam eaque. Optio neque commodi.', '12')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие24', '3600', 'Molestiae eveniet nesciunt. Temporibus suscipit et aspernatur natus earum impedit.', '25')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие25', '10000', 'Nisi facere facilis dignissimos asperiores. Placeat quasi nihil iure.', '41')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие26', '5400', 'Culpa laborum quasi molestiae. Est tempore dolor at. Ratione fuga dicta assumenda delectus.', '27')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие27', '1000', 'Quisquam soluta excepturi harum a soluta. Exercitationem at error perspiciatis odit.', '41')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие28', '1300', 'Assumenda cupiditate modi impedit sapiente sint. Labore sapiente blanditiis vitae ipsum at.', '16')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие29', '2000', 'Soluta delectus animi. Repellendus earum occaecati debitis earum in illum veniam.', '8')
INSERT INTO Product (product_name, product_price, product_desc, product_rem) VALUES('Изделие30', '1100', 'Possimus sit tempore repellendus temporibus perferendis autem.', '16')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('2', '3', '1')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('9', '13', '1')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('9', '2', '7')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('1', '20', '5')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('5', '16', '1')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('18', '13', '17')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('11', '5', '16')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('1', '9', '6')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('8', '4', '8')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('4', '6', '13')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('11', '20', '30')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('6', '19', '25')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('19', '20', '17')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('2', '20', '22')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('12', '2', '12')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('10', '7', '18')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('17', '6', '7')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('19', '15', '2')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('13', '1', '13')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('10', '6', '26')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('8', '2', '4')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('11', '4', '14')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('15', '7', '2')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('5', '5', '8')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('16', '6', '19')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('13', '6', '4')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('6', '7', '28')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('7', '11', '12')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('1', '13', '16')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('8', '18', '26')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('7', '16', '29')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('16', '11', '22')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('9', '13', '4')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('6', '3', '23')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('20', '17', '22')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('10', '2', '30')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('17', '13', '10')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('5', '18', '4')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('8', '11', '28')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('8', '15', '30')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('4', '2', '5')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('7', '16', '30')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('16', '2', '3')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('8', '8', '25')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('13', '2', '17')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('8', '17', '25')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('19', '8', '4')
INSERT INTO Orders_product (orders_product_amount, orders_id, product_id) VALUES('3', '9', '14')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь1', '4', '1', '4')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь2', '4', '4', '8')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь3', '2', '3', '19')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь4', '3', '1', '27')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь5', '4', '4', '4')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь6', '4', '5', '14')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь7', '1', '1', '9')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь8', '1', '1', '1')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь9', '4', '1', '1')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь10', '4', '3', '18')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь11', '4', '3', '29')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь12', '4', '2', '24')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь13', '3', '3', '27')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь14', '3', '2', '26')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь15', '1', '4', '30')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь16', '2', '1', '17')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь17', '4', '4', '26')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь18', '1', '2', '16')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь19', '4', '4', '22')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь20', '4', '5', '26')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь21', '1', '3', '17')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь22', '4', '1', '2')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь23', '1', '2', '19')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь24', '3', '5', '4')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь25', '2', '4', '2')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь26', '3', '4', '2')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь27', '3', '1', '19')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь28', '3', '1', '6')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь29', '3', '2', '23')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь30', '2', '4', '6')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь31', '3', '2', '2')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь32', '3', '4', '1')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь33', '3', '3', '2')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь34', '4', '1', '1')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь35', '1', '1', '6')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь36', '1', '2', '30')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь37', '4', '5', '21')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь38', '2', '5', '8')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь39', '1', '2', '25')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь40', '2', '4', '12')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь41', '1', '5', '23')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь42', '2', '3', '4')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь43', '2', '1', '1')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь44', '3', '1', '17')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь45', '1', '4', '10')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь46', '3', '2', '20')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь47', '1', '3', '20')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь48', '4', '4', '1')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь49', '4', '2', '1')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь50', '4', '1', '29')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь51', '3', '3', '12')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь52', '1', '1', '27')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь53', '1', '4', '9')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь54', '1', '3', '6')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь55', '2', '3', '20')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь56', '3', '5', '17')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь57', '1', '3', '23')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь58', '4', '2', '11')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь59', '1', '1', '12')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь60', '4', '4', '23')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь61', '1', '4', '5')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь62', '2', '2', '29')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь63', '4', '3', '27')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь64', '1', '3', '28')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь65', '2', '4', '28')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь66', '3', '3', '1')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь67', '4', '2', '1')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь68', '2', '4', '9')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь69', '1', '5', '1')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь70', '3', '3', '25')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь71', '4', '2', '7')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь72', '3', '4', '5')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь73', '3', '2', '25')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь74', '2', '5', '28')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь75', '2', '1', '9')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь76', '3', '1', '28')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь77', '2', '2', '9')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь78', '1', '4', '25')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь79', '4', '2', '7')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь80', '2', '2', '16')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь81', '3', '2', '21')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь82', '2', '1', '18')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь83', '4', '3', '3')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь84', '4', '3', '2')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь85', '3', '2', '29')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь86', '3', '3', '28')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь87', '4', '2', '19')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь88', '2', '3', '19')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь89', '4', '1', '14')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь90', '1', '2', '7')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь91', '2', '3', '18')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь92', '2', '4', '7')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь93', '1', '2', '28')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь94', '3', '3', '22')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь95', '2', '4', '20')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь96', '3', '2', '28')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь97', '2', '3', '29')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь98', '4', '4', '29')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь99', '4', '1', '24')
INSERT INTO Component (component_name, component_time, workshop_id, product_id) VALUES('Деталь100', '4', '3', '4')
