INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Октябрина Робертовна Сысоева', '4088582', 'ст. Соликамск, бул. 70 лет Октября, д. 236 стр. 6, 632421', '+7 428 835 5211', '9601 291590')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Семенова Елена Львовна', '6255864', 'с. Рубцовск, бул. Воровского, д. 37 стр. 749, 379755', '+7 (751) 157-7603', '6720 692286')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Кудрявцев Дементий Виленович', '2201115', 'к. Липецк, пер. Алтайский, д. 9, 818532', '87157348184', '6621 618988')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Рогов Максим Харлампович', '2590835', 'клх Нерчинск, пр. Свободы, д. 782, 879827', '8 (430) 289-90-69', '9108 387796')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Наина Вениаминовна Лыткина', '8738273', 'п. Троицк (Моск.), алл. Металлистов, д. 93 стр. 35, 014333', '8 (753) 307-7833', '8405 077346')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Никонова Валерия Даниловна', '9534987', 'ст. Когалым, пер. Чехова, д. 5/4, 555989', '+7 745 238 3850', '2803 161714')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Третьякова Жанна Львовна', '7051361', 'г. Тура, ш. Ермака, д. 3/2, 254907', '+7 438 495 9367', '4212 477049')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Зинаида Никифоровна Котова', '7011255', 'п. Калачинск, алл. Горная, д. 7/7, 988082', '+79928869176', '4601 902759')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Ратибор Федосьевич Яковлев', '1214446', 'г. Великие Луки, ш. Советов, д. 403 к. 32, 470018', '8 (882) 025-00-15', '8011 697299')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Дорофеев Творимир Валентинович', '8457511', 'г. Касимов, ул. Главная, д. 999, 845583', '8 (852) 264-1972', '2701 623358')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Варфоломей Анисимович Романов', '8117172', 'д. Кингисепп, пр. Дарвина, д. 2/7, 906584', '+7 872 006 9877', '6304 993412')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Пахомов Лонгин Богданович', '3493724', 'ст. Борзя, ш. Красноярское, д. 1, 546894', '8 (088) 117-8919', '9608 197542')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Мельникова Наина Аскольдовна', '3595110', 'клх Каргополь, пр. Строительный, д. 1 к. 81, 531526', '+7 878 918 82 10', '3917 962121')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Емельянова Варвара Романовна', '9425580', 'к. Соболево, наб. Урожайная, д. 8/3, 203146', '80981893693', '4108 811295')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Белов Стоян Валерьянович', '8778983', 'г. Кузнецк, ш. Морозова, д. 18 стр. 28, 474189', '8 679 089 49 51', '8408 081523')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Григорьев Влас Федотович', '6552331', 'г. Урай, ул. Заводская, д. 23, 813182', '+7 071 233 57 36', '7207 261696')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Ефимов Ким Яковлевич', '6825814', 'г. Сортавала, ш. Высокое, д. 8, 596650', '8 719 166 8299', '0910 842948')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('г-н Князев Афанасий Афанасьевич', '7562593', 'к. Сортавала, наб. Алтайская, д. 8/2 к. 12, 692474', '+76287930402', '3619 899272')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Прасковья Аркадьевна Щукина', '3201404', 'д. Соловки, бул. Нефтяников, д. 6 к. 14, 340486', '+7 (230) 501-75-30', '1521 383876')
INSERT INTO Customer (customer_name, customer_inn, customer_addr, customer_tel, customer_passport) VALUES('Нонна Яковлевна Цветкова', '7572124', 'клх Нерчинск, пр. Поселковый, д. 2 к. 773, 589471', '+7 707 856 4065', '1517 538943')
INSERT INTO Workshop (workshop_name, workshop_dir_name, workshop_addr) VALUES('Цех1', 'Туров Игорь Егорович', 'клх Россошь, ул. Халтурина, д. 20 к. 48, 071686')
INSERT INTO Workshop (workshop_name, workshop_dir_name, workshop_addr) VALUES('Цех2', 'Христофор Ильич Богданов', 'клх Нижневартовск, ш. Аэродромное, д. 424 к. 2, 700574')
INSERT INTO Workshop (workshop_name, workshop_dir_name, workshop_addr) VALUES('Цех3', 'Корнилов Трофим Васильевич', 'п. Мытищи, пр. Нефтяников, д. 7/3 стр. 7/3, 592449')
INSERT INTO Workshop (workshop_name, workshop_dir_name, workshop_addr) VALUES('Цех4', 'Дорофеев Руслан Григорьевич', 'д. Шатура, наб. Ясная, д. 6/3 к. 434, 996696')
INSERT INTO Workshop (workshop_name, workshop_dir_name, workshop_addr) VALUES('Цех5', 'Элеонора Болеславовна Баранова', 'п. Советский, ш. Северное, д. 1/5 к. 495, 914571')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Орлов Добромысл Владиленович', '3289598', '+7 089 436 75 61', '4105 932641', 'с. Муром, бул. Горный, д. 693 стр. 8/6, 053610', '3')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Осипов Афанасий Александрович', '5498441', '+7 (122) 024-47-28', '5605 892319', 'д. Северодвинск, наб. Терешковой, д. 34 стр. 465, 731857', '2')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Аркадий Ануфриевич Некрасов', '1851648', '+7 (256) 786-9211', '7913 525498', 'п. Луга, алл. Угольная, д. 99 к. 7/4, 835948', '4')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Семен Тарасович Виноградов', '7399366', '+7 267 228 5240', '6909 680386', 'ст. Тверь, наб. Волгоградская, д. 844, 041356', '1')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Полина Федоровна Бобылева', '4197939', '8 860 008 5811', '3016 952608', 'п. Салават, пер. 50 лет ВЛКСМ, д. 1/3 стр. 34, 704213', '5')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Лора Константиновна Лыткина', '5488040', '+7 (756) 786-85-05', '4308 841660', 'с. Инта, пр. Огородный, д. 5/4 к. 1, 856532', '2')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Уварова Фёкла Матвеевна', '6137761', '+7 916 437 41 46', '9401 657464', 'д. Мыс Шмидта, пер. Ульяновский, д. 3/1, 382554', '3')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Фёкла Тимуровна Николаева', '3437031', '8 973 657 96 33', '3406 152206', 'клх Соловки, алл. Загородная, д. 4/9, 425612', '4')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Соколов Остап Власович', '6408184', '+7 (084) 590-7290', '4801 139644', 'д. Саров (Морд.), ул. Каштановая, д. 9/2, 322643', '5')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Поляков Август Антипович', '4735559', '+7 160 321 57 47', '0314 280886', 'к. Хужир, ш. Ленское, д. 9/5 стр. 22, 922369', '4')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Стрелкова Нина Владиславовна', '9779142', '+75713779734', '5810 816246', 'д. Воркута, алл. Карьерная, д. 617 к. 2, 361856', '4')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Ульяна Львовна Новикова', '6699312', '85817274081', '0413 357056', 'п. Тихвин, ул. Пригородная, д. 31 к. 3, 977489', '3')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('тов. Богданов Ладимир Глебович', '9796814', '8 539 418 2318', '6301 058702', 'клх Ребриха, ш. Горняцкое, д. 2/9 стр. 8, 769381', '2')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Устинов Добромысл Ефремович', '6193580', '+7 409 589 8516', '5513 297750', 'г. Мураши, пр. Каштановый, д. 1/5 к. 6, 858689', '4')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Мишина Нонна Болеславовна', '8432389', '8 057 763 11 71', '6202 584744', 'с. Палана, бул. Амурский, д. 4 к. 63, 420739', '2')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Кира Юрьевна Цветкова', '3777043', '+7 (162) 504-0750', '5204 401134', 'д. Челюскин, пр. Таежный, д. 8/1, 737357', '5')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Архипов Амос Виленович', '8219976', '8 314 149 9821', '9604 878994', 'с. Сасово, пер. Промышленный, д. 88 стр. 18, 026904', '3')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Матвеев Любосмысл Ефимович', '1101968', '+7 (229) 942-65-31', '0204 032848', 'п. Салават, бул. Терешковой, д. 432 стр. 533, 458284', '2')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Богданов Пров Владиславович', '3889536', '+7 912 776 4668', '3613 978805', 'клх Неплюевка, алл. 40 лет Победы, д. 8/6 к. 828, 164584', '3')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Соловьев Макар Александрович', '9951007', '83339873325', '1307 203979', 'ст. Горячий Ключ, ш. Красноармейское, д. 5 к. 8, 219424', '5')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Татьяна Оскаровна Мухина', '7479887', '+7 (745) 920-0714', '2421 764518', 'г. Енисейск, ул. Проточная, д. 375, 940749', '4')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Панфилова Вероника Ивановна', '6220456', '+7 (561) 202-7067', '2105 689434', 'к. Нефтегорск (Самар.), ул. Грибоедова, д. 22, 091277', '1')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Поликарп Яковлевич Козлов', '9902660', '80741686874', '5002 279835', 'п. Гремячинск (Бурят.), бул. Космический, д. 7/4, 143322', '2')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Эрнст Чеславович Кошелев', '8385153', '+7 537 643 6248', '4516 747132', 'с. Усть-Калманка, алл. Кооперативная, д. 8 стр. 8/5, 130807', '5')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Осип Артёмович Жданов', '4570742', '8 499 083 07 52', '9804 737899', 'п. Петухово, пер. Физкультурный, д. 21, 325452', '1')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Антип Демидович Евсеев', '4752677', '8 (436) 267-0373', '5408 870694', 'п. Армавир, наб. Минская, д. 5 к. 547, 916013', '3')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Маркова Оксана Дмитриевна', '2433847', '87572171274', '4801 774297', 'ст. Бологое, пр. Пионерский, д. 71 стр. 64, 464301', '2')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Михеева Лора Геннадьевна', '6953140', '+7 (097) 217-07-66', '0202 221447', 'п. Хабаровск, алл. Гвардейская, д. 18, 099590', '2')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Голубев Борислав Феликсович', '4551979', '83959363307', '3606 452886', 'к. Кимры, наб. Строительная, д. 554 стр. 87, 204395', '1')
INSERT INTO Worker (worker_name, worker_inn, worker_tel, worker_passport, worker_addr, workshop_id) VALUES('Потап Ерофеевич Беспалов', '6334629', '8 927 840 47 83', '6117 384894', 'клх Астрахань, пер. Карла Либкнехта, д. 1/1, 151630', '5')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Ноябрьск, наб. 9 мая, д. 4/4 к. 6/1, 434000', '1108 609464', '2019-06-12', '17')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Валаам, пер. Крымский, д. 3/8, 931430', '6119 368514', '2018-12-01', '3')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('клх Сортавала, ул. Фурманова, д. 790 стр. 43, 088403', '0804 670684', '2020-06-10', '17')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('п. Оса, ул. Физкультурная, д. 728 стр. 8, 634082', '0409 816046', '2017-06-26', '18')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('п. Подольск, пр. Саратовский, д. 69 стр. 126, 812929', '4701 309954', '2020-08-13', '2')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('ст. Шелагонцы, ш. Панфилова, д. 604 к. 887, 609950', '3510 264321', '2018-08-20', '20')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Фатеж, ш. Степана Разина, д. 766, 768897', '9601 305504', '2020-02-17', '18')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Апшеронск, бул. Полярный, д. 8/8, 401855', '6212 433763', '2019-03-22', '18')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('ст. Быково (метеост.), наб. Тихая, д. 47 к. 720, 192614', '3418 890944', '2018-09-08', '10')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Егорьевск, ш. Абрикосовое, д. 705, 590245', '1906 382398', '2021-12-06', '15')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Кыштым, наб. Киевская, д. 6 стр. 12, 941173', '2615 201757', '2019-03-10', '2')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Североморск, алл. Шахтерская, д. 8/1, 929468', '0802 128228', '2021-12-04', '5')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('с. Баргузин, наб. Азовская, д. 670 стр. 4/6, 476695', '5019 267015', '2021-12-08', '3')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Жигулевск, пер. Павлика Морозова, д. 43 к. 8/7, 677549', '3219 020459', '2018-12-19', '14')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('с. Томск, наб. Маяковского, д. 871, 010334', '5605 047025', '2021-08-24', '2')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('п. Плесецк, наб. Сенная, д. 537, 968389', '7517 483410', '2018-07-20', '18')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('ст. Рославль, пер. Жданова, д. 5/3 к. 671, 604911', '6105 456034', '2021-03-25', '10')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('клх Хасавюрт, пер. Вокзальный, д. 8 стр. 95, 066636', '2207 665246', '2019-09-30', '9')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('клх Салават, наб. Мирная, д. 67, 550609', '4110 857627', '2019-08-21', '20')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('клх Вязьма, пр. Добролюбова, д. 12 к. 146, 597684', '3715 054764', '2018-12-02', '14')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Ачхой Мартан, пер. Кутузова, д. 93, 644139', '0815 464548', '2018-04-03', '13')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('д. Лянтор, ул. Ясная, д. 4/9, 197919', '3204 387152', '2019-12-21', '1')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('д. Малая Вишера, пер. Панфилова, д. 4 к. 6, 246408', '9318 581726', '2018-04-05', '16')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Кирово-Чепецк, алл. Заводская, д. 739, 378226', '9811 366102', '2017-09-24', '8')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('с. Новокузнецк, бул. Севастопольский, д. 82 стр. 16, 530004', '9906 046098', '2020-01-19', '1')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('п. Артем, ш. Пролетарское, д. 4/4 к. 9/3, 826566', '7204 013103', '2018-08-23', '1')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('с. Лесной (Сверд.), ул. Рылеева, д. 6 стр. 3/6, 838779', '8806 622433', '2019-03-26', '16')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('д. Сасово, ул. Ростовская, д. 3/6 к. 6/5, 978459', '5508 931397', '2019-10-19', '17')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Кыштым, бул. Калужский, д. 6 к. 8/3, 853204', '0901 335265', '2017-06-26', '20')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Яшкуль, наб. Тульская, д. 580 к. 164, 589383', '2906 203078', '2018-08-11', '18')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('д. Сладково, алл. Просвещения, д. 116 к. 72, 774924', '9414 947080', '2018-12-27', '4')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('клх Шуя, ул. Проезжая, д. 7/6, 408009', '3521 722095', '2021-08-07', '12')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Томпа, бул. Розы Люксембург, д. 8/7 стр. 720, 376857', '6719 306383', '2017-12-25', '1')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('д. Горячинск, ул. Прохладная, д. 5/3 стр. 338, 506896', '2711 708319', '2018-10-31', '1')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('д. Бавлы, бул. Майский, д. 345 стр. 743, 026336', '0901 894771', '2021-07-23', '2')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Чебаркуль, пер. Енисейский, д. 9 стр. 44, 668856', '5314 701919', '2018-10-01', '14')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('ст. Кедровый, бул. Короткий, д. 27, 608143', '8718 970899', '2017-11-01', '4')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Поронайск, ш. Железнодорожное, д. 575, 266706', '6218 355265', '2017-11-22', '8')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('п. Борзя, алл. Прохладная, д. 7/8 стр. 6, 861250', '5119 544999', '2016-12-26', '10')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('клх Дубна, ул. Щорса, д. 6 стр. 6, 417525', '5805 594377', '2017-01-01', '13')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Усинск, ш. Мичурина, д. 126, 866809', '6902 572778', '2018-04-22', '9')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('ст. Салават, ш. Ярославское, д. 22 к. 74, 092526', '8914 971602', '2018-09-12', '7')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Бирск, пр. Крестьянский, д. 6 к. 740, 810560', '9614 092973', '2021-01-23', '19')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Таштагол, пер. Ермака, д. 3 стр. 52, 485940', '6508 852316', '2017-10-21', '11')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('с. Ишим, бул. Димитрова, д. 51 стр. 480, 913037', '1809 039986', '2020-08-09', '11')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('д. Смирных, ш. Карла Либкнехта, д. 4/7 стр. 5, 089835', '8702 634867', '2020-03-07', '12')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('к. Павловская, наб. Советов, д. 6 стр. 2/2, 164622', '3204 328389', '2017-03-12', '8')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('г. Нефтеюганск, алл. Молодежная, д. 59 к. 874, 028840', '2411 674492', '2018-10-06', '18')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('ст. Палана, пер. Красноярский, д. 24 к. 841, 816804', '7510 405293', '2021-09-12', '11')
INSERT INTO Orders (orders_addr, orders_passport, orders_date, customer_id) VALUES('с. Юровск, ш. Буденного, д. 599 к. 3, 909274', '8408 065757', '2019-01-29', '2')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие1', '4200', 'Dignissimos illum alias aliquid blanditiis. Commodi quae quod architecto.', '4')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие2', '2300', 'Ullam dolore temporibus alias.', '17')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие3', '5600', 'Consectetur voluptas qui optio expedita. Eius deleniti tempora deserunt dolorem.', '1')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие4', '9300', 'Nesciunt ipsum aspernatur minus ipsam impedit. Ratione temporibus sed.', '6')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие5', '8100', 'Eius saepe tenetur. Consectetur magni accusantium molestias aperiam. Distinctio cum eius neque.', '4')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие6', '4400', 'Sed fugit quae sunt rem reprehenderit. Quae neque ratione.', '19')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие7', '900', 'Veniam in expedita. Ut exercitationem assumenda optio exercitationem esse illo consectetur.', '20')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие8', '9700', 'Totam corporis at saepe consectetur doloribus inventore. In cupiditate debitis.', '32')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие9', '1800', 'Deleniti animi nam ut sapiente. Reiciendis nesciunt facere magni. Nostrum totam nam tempora amet.', '46')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие10', '3600', 'Corporis quas necessitatibus in. Dicta esse deserunt veniam dicta doloribus sapiente.', '21')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие11', '7100', 'Esse enim dicta illum nisi. Exercitationem tempora at ratione.', '50')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие12', '7100', 'Delectus voluptatem inventore assumenda.', '13')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие13', '3500', 'Voluptatem quaerat excepturi voluptates nisi. Ratione quia quo possimus beatae.', '39')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие14', '8000', 'Veritatis officia voluptates facilis. Suscipit adipisci optio alias.', '49')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие15', '9900', 'Nostrum doloribus alias id voluptas mollitia modi. Quidem esse perferendis sapiente natus expedita.', '26')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие16', '3500', 'Deleniti impedit iusto. Totam aliquam impedit tenetur libero quibusdam non ipsa.', '30')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие17', '8100', 'Deleniti magnam et voluptates. Amet dicta soluta fugit quisquam quibusdam perspiciatis.', '20')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие18', '1200', 'Totam asperiores molestias deleniti vel perspiciatis quasi. Sit harum nostrum.', '16')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие19', '4900', 'Sapiente eius cum aliquam.
Odio consequatur dolor veniam optio eius.', '22')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие20', '10000', 'Dolores quibusdam omnis aperiam. Vitae autem ab dolor rerum. Pariatur quas consectetur sed quaerat.', '29')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие21', '7700', 'Totam iusto suscipit asperiores omnis. Quos earum tempore laudantium facilis impedit.', '23')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие22', '1600', 'Recusandae similique accusamus dolorem neque reprehenderit sunt.', '47')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие23', '5000', 'Fugit hic tenetur omnis odio eaque.', '41')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие24', '3900', 'Totam odio libero ducimus minus optio maiores.', '41')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие25', '4700', 'Consectetur odit a nisi ab omnis. Non facere et reprehenderit quod blanditiis velit.', '13')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие26', '8900', 'Ipsa quasi quisquam. Qui expedita quia voluptatibus voluptatibus rerum asperiores suscipit.', '33')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие27', '9800', 'Sequi sequi quod eaque laudantium natus.', '1')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие28', '3600', 'Vitae numquam saepe voluptatum.', '6')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие29', '4600', 'Ducimus in ipsam.
Voluptatibus occaecati esse. Dignissimos tempore at odio.', '39')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие30', '1500', 'Quas odit sit sit reprehenderit consequatur.', '3')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие31', '7900', 'Ratione in pariatur explicabo.', '12')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие32', '5000', 'Nam nobis optio optio voluptates esse. Dolor quasi perferendis enim iusto mollitia.', '43')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие33', '7100', 'Ea nobis consequuntur delectus quod exercitationem nulla. Molestiae eaque incidunt sapiente.', '44')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие34', '1600', 'Occaecati alias dignissimos iste ratione molestias consectetur nostrum.', '13')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие35', '2800', 'Quo nobis at neque sapiente voluptatibus. Non quas occaecati sit error.', '33')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие36', '1500', 'Alias repudiandae esse accusantium nobis est. Quos odit explicabo quas.', '48')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие37', '2100', 'Minus in aspernatur accusantium culpa. Officiis voluptate consectetur totam.', '21')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие38', '700', 'Ut fuga provident rerum quod. Quae laborum iure corporis. Sapiente culpa at.', '15')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие39', '7300', 'Doloribus hic repellendus impedit assumenda atque corrupti.
At corporis beatae accusamus.', '32')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие40', '4200', 'Deserunt quasi neque perspiciatis hic voluptatem occaecati.', '20')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие41', '600', 'Et sit commodi. Molestias aliquam sit sit illo aperiam. Odio officia sed deserunt ea dolores.', '29')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие42', '8600', 'Non quis omnis harum necessitatibus sint impedit tempora. Eveniet quod dolore neque culpa.', '12')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие43', '5600', 'Exercitationem nostrum deserunt velit voluptas. Aliquid maiores hic velit doloremque.', '20')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие44', '9100', 'Cum cupiditate harum animi cupiditate voluptates iure.', '15')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие45', '7000', 'Harum cumque hic incidunt qui accusamus autem. Corrupti sit assumenda nulla sed.', '23')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие46', '2100', 'Repellendus laboriosam atque libero ratione laudantium quia.', '46')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие47', '6700', 'Repellendus rerum porro veritatis. Eligendi consectetur optio quia sed.', '25')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие48', '4400', 'Nesciunt quos vero enim aperiam beatae delectus. Praesentium magni labore. Nihil qui repellendus.', '9')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие49', '8500', 'Asperiores incidunt iure exercitationem. Illo consequatur quos cum voluptate temporibus natus.', '8')
INSERT INTO Product (product_name, product_price, product_desc, product_quantity) VALUES('Изделие50', '5200', 'Mollitia placeat quidem.', '3')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('19', '43', '39')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('8', '45', '45')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('17', '2', '14')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '31', '31')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('2', '48', '38')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '41', '4')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '43', '20')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('19', '47', '24')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('5', '25', '45')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('14', '48', '25')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '30', '50')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '40', '27')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('5', '50', '48')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '19', '12')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('15', '22', '3')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('15', '48', '1')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('14', '42', '34')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '25', '9')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '7', '35')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '50', '7')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('20', '23', '40')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('12', '35', '17')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '15', '42')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('18', '5', '39')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('20', '11', '27')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '3', '22')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('16', '16', '29')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('19', '11', '34')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('15', '3', '40')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '25', '40')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('3', '8', '7')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '27', '30')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('5', '31', '28')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('14', '42', '28')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '12', '4')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '49', '9')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '5', '34')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('7', '29', '45')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('8', '1', '45')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '26', '34')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '15', '30')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '48', '34')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('19', '39', '3')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('18', '49', '28')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('19', '16', '49')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '34', '2')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '7', '19')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '36', '22')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '44', '18')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('3', '17', '1')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('12', '30', '46')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '6', '9')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '42', '45')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('17', '32', '46')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('12', '40', '41')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('2', '4', '23')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('2', '4', '11')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('7', '1', '39')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '2', '22')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('18', '14', '28')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('3', '11', '40')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('16', '39', '43')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('20', '38', '43')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('17', '3', '42')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('20', '23', '35')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '9', '47')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('7', '42', '2')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('5', '20', '5')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('3', '4', '13')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('17', '28', '36')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('20', '34', '50')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('3', '14', '36')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('5', '31', '17')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '33', '38')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('7', '24', '19')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('2', '38', '6')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('18', '27', '22')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('3', '45', '12')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('14', '50', '6')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '43', '22')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('2', '23', '11')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('15', '49', '43')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '10', '49')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('4', '49', '1')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('16', '15', '6')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('20', '22', '48')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '15', '38')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('12', '29', '4')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('14', '48', '29')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('15', '38', '18')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '13', '22')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('14', '15', '4')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('16', '19', '2')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('15', '8', '13')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('5', '8', '11')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('4', '49', '24')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('18', '27', '39')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('7', '14', '2')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('18', '26', '23')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('19', '10', '17')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '24', '38')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '44', '2')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('12', '17', '35')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('14', '29', '41')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '49', '8')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '37', '30')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '6', '33')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('18', '4', '22')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '16', '18')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '14', '4')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('5', '28', '39')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '4', '3')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('8', '30', '16')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('16', '31', '15')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('17', '49', '26')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('17', '32', '25')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('2', '21', '22')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '43', '18')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '13', '4')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '12', '2')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '36', '32')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '14', '21')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '29', '32')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '50', '47')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('7', '42', '31')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('3', '7', '47')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('8', '42', '26')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '14', '48')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '50', '22')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('19', '10', '9')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('2', '3', '32')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('15', '18', '1')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '10', '38')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '28', '22')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('16', '42', '35')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '35', '39')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('14', '4', '35')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '18', '5')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('7', '33', '42')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('2', '42', '10')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '15', '50')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '25', '20')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('8', '32', '20')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('17', '10', '16')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('8', '38', '23')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '30', '2')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('8', '5', '10')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('8', '47', '15')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('18', '45', '25')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('20', '22', '36')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('20', '30', '20')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('2', '42', '1')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '50', '24')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('19', '36', '15')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '5', '27')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '45', '27')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '25', '28')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('5', '10', '8')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('1', '28', '10')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('14', '5', '19')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('15', '4', '1')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('3', '9', '41')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('7', '38', '38')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '18', '20')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('11', '49', '11')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('12', '43', '3')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '21', '30')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('4', '21', '33')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('8', '5', '49')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('16', '16', '47')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '26', '50')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('16', '30', '14')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('13', '1', '17')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('20', '38', '33')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('14', '29', '24')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('20', '17', '18')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('4', '21', '38')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('9', '48', '24')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('15', '22', '4')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('7', '1', '24')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '12', '43')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '31', '30')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('6', '46', '37')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('18', '20', '45')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('4', '30', '40')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('10', '25', '34')
INSERT INTO Orders_product (orders_product_quantity, orders_id, product_id) VALUES('18', '4', '10')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь1', '4', '37', '1', '18')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь2', '2', '14', '5', '3')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь3', '3', '47', '2', '3')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь4', '2', '46', '3', '9')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь5', '3', '24', '4', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь6', '2', '31', '2', '21')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь7', '3', '6', '4', '19')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь8', '1', '6', '5', '47')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь9', '2', '35', '1', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь10', '1', '18', '1', '13')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь11', '3', '27', '1', '46')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь12', '1', '34', '3', '35')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь13', '2', '12', '4', '13')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь14', '2', '17', '5', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь15', '2', '0', '3', '41')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь16', '3', '19', '3', '42')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь17', '3', '33', '3', '42')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь18', '3', '23', '2', '31')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь19', '1', '19', '2', '41')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь20', '4', '10', '2', '43')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь21', '1', '13', '1', '45')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь22', '2', '48', '5', '19')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь23', '2', '2', '4', '16')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь24', '3', '22', '2', '22')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь25', '4', '3', '5', '26')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь26', '2', '35', '3', '12')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь27', '3', '22', '4', '2')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь28', '1', '11', '5', '2')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь29', '3', '17', '4', '6')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь30', '4', '30', '1', '37')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь31', '1', '43', '5', '42')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь32', '4', '41', '3', '42')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь33', '1', '45', '3', '5')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь34', '2', '12', '3', '31')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь35', '3', '2', '1', '30')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь36', '4', '17', '2', '45')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь37', '3', '17', '4', '2')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь38', '4', '18', '5', '5')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь39', '4', '33', '3', '43')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь40', '4', '14', '3', '13')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь41', '4', '38', '3', '41')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь42', '1', '21', '5', '26')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь43', '3', '20', '3', '30')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь44', '1', '45', '4', '5')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь45', '3', '33', '1', '36')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь46', '1', '29', '5', '3')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь47', '3', '36', '3', '10')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь48', '1', '11', '3', '2')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь49', '1', '36', '4', '48')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь50', '2', '8', '2', '22')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь51', '3', '37', '5', '25')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь52', '4', '24', '2', '11')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь53', '4', '8', '4', '20')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь54', '2', '17', '3', '19')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь55', '2', '40', '5', '2')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь56', '1', '38', '3', '13')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь57', '3', '33', '2', '23')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь58', '2', '8', '2', '20')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь59', '4', '45', '2', '29')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь60', '3', '6', '2', '39')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь61', '2', '33', '4', '46')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь62', '2', '22', '4', '28')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь63', '3', '42', '3', '12')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь64', '3', '28', '5', '29')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь65', '3', '30', '5', '30')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь66', '3', '23', '5', '7')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь67', '4', '45', '2', '33')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь68', '1', '50', '1', '43')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь69', '2', '35', '3', '31')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь70', '3', '36', '4', '9')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь71', '1', '48', '2', '11')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь72', '4', '50', '5', '40')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь73', '3', '4', '3', '30')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь74', '2', '40', '4', '34')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь75', '2', '33', '5', '23')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь76', '2', '27', '5', '18')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь77', '2', '8', '4', '33')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь78', '4', '11', '3', '37')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь79', '2', '19', '1', '41')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь80', '1', '1', '3', '40')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь81', '4', '4', '2', '38')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь82', '4', '14', '1', '12')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь83', '2', '16', '1', '25')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь84', '2', '30', '1', '47')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь85', '4', '11', '1', '45')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь86', '2', '7', '5', '10')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь87', '3', '37', '5', '13')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь88', '3', '16', '1', '6')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь89', '3', '17', '3', '20')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь90', '4', '34', '3', '18')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь91', '1', '30', '4', '44')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь92', '1', '44', '3', '5')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь93', '1', '30', '4', '16')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь94', '3', '36', '2', '10')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь95', '2', '28', '1', '25')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь96', '4', '47', '5', '36')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь97', '3', '42', '2', '11')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь98', '3', '18', '5', '16')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь99', '4', '2', '3', '24')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь100', '4', '37', '4', '31')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь101', '1', '6', '2', '15')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь102', '2', '25', '5', '38')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь103', '4', '47', '5', '29')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь104', '1', '47', '5', '9')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь105', '4', '39', '2', '19')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь106', '1', '42', '2', '1')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь107', '3', '24', '4', '27')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь108', '1', '8', '1', '50')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь109', '2', '39', '1', '17')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь110', '2', '23', '3', '42')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь111', '2', '26', '1', '32')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь112', '3', '22', '4', '43')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь113', '4', '38', '2', '25')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь114', '2', '11', '5', '10')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь115', '1', '27', '2', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь116', '3', '0', '1', '22')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь117', '4', '2', '3', '49')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь118', '2', '19', '2', '8')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь119', '4', '46', '1', '1')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь120', '3', '9', '3', '45')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь121', '2', '23', '4', '31')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь122', '1', '34', '3', '16')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь123', '2', '34', '1', '31')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь124', '2', '14', '1', '29')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь125', '1', '27', '1', '11')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь126', '3', '10', '5', '35')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь127', '2', '18', '5', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь128', '1', '20', '1', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь129', '1', '14', '4', '19')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь130', '1', '41', '3', '15')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь131', '2', '19', '5', '15')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь132', '4', '27', '1', '39')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь133', '2', '40', '4', '23')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь134', '3', '2', '1', '24')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь135', '4', '40', '2', '22')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь136', '1', '14', '3', '3')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь137', '2', '42', '4', '43')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь138', '3', '45', '3', '21')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь139', '2', '36', '5', '47')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь140', '2', '40', '4', '5')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь141', '2', '14', '3', '35')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь142', '2', '11', '1', '37')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь143', '1', '50', '4', '8')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь144', '3', '7', '3', '6')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь145', '3', '24', '3', '7')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь146', '3', '13', '5', '34')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь147', '3', '28', '1', '2')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь148', '1', '12', '4', '24')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь149', '2', '7', '3', '41')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь150', '4', '14', '5', '38')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь151', '2', '10', '3', '12')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь152', '2', '19', '4', '40')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь153', '3', '6', '5', '19')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь154', '1', '42', '3', '1')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь155', '2', '37', '2', '38')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь156', '4', '11', '5', '9')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь157', '3', '49', '3', '5')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь158', '1', '3', '3', '30')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь159', '4', '48', '2', '33')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь160', '2', '20', '2', '42')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь161', '2', '7', '2', '42')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь162', '3', '48', '4', '30')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь163', '3', '47', '5', '19')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь164', '1', '25', '4', '7')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь165', '3', '3', '4', '48')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь166', '1', '2', '4', '43')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь167', '2', '24', '5', '28')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь168', '3', '38', '5', '26')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь169', '3', '12', '3', '22')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь170', '3', '43', '4', '33')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь171', '4', '12', '2', '22')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь172', '2', '23', '3', '41')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь173', '3', '28', '3', '24')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь174', '3', '37', '2', '44')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь175', '2', '15', '5', '16')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь176', '2', '17', '1', '47')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь177', '2', '28', '5', '26')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь178', '2', '42', '4', '27')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь179', '4', '38', '2', '23')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь180', '4', '30', '4', '32')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь181', '1', '9', '5', '49')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь182', '2', '0', '5', '37')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь183', '4', '23', '2', '33')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь184', '3', '32', '3', '6')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь185', '1', '34', '4', '45')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь186', '4', '48', '3', '33')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь187', '1', '45', '5', '19')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь188', '3', '14', '3', '35')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь189', '2', '48', '3', '36')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь190', '4', '11', '5', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь191', '4', '16', '5', '36')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь192', '3', '49', '2', '19')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь193', '4', '32', '1', '11')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь194', '2', '15', '2', '17')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь195', '4', '32', '4', '22')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь196', '3', '36', '4', '40')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь197', '2', '9', '1', '18')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь198', '2', '6', '2', '40')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь199', '2', '14', '3', '25')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь200', '1', '5', '3', '20')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь201', '4', '44', '1', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь202', '3', '11', '2', '46')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь203', '2', '9', '2', '22')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь204', '1', '44', '2', '35')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь205', '2', '19', '1', '24')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь206', '2', '24', '1', '27')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь207', '4', '39', '3', '41')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь208', '4', '15', '2', '34')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь209', '1', '25', '4', '2')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь210', '2', '30', '4', '29')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь211', '2', '26', '5', '15')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь212', '3', '16', '1', '24')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь213', '4', '24', '1', '46')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь214', '4', '32', '4', '26')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь215', '3', '0', '5', '33')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь216', '2', '41', '4', '25')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь217', '3', '39', '5', '18')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь218', '1', '35', '4', '15')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь219', '4', '36', '1', '28')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь220', '2', '10', '5', '38')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь221', '3', '40', '2', '2')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь222', '4', '16', '1', '11')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь223', '4', '33', '3', '12')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь224', '3', '11', '4', '9')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь225', '4', '42', '1', '26')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь226', '4', '16', '3', '21')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь227', '4', '23', '4', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь228', '3', '3', '5', '16')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь229', '3', '18', '3', '39')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь230', '4', '36', '4', '45')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь231', '2', '30', '1', '3')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь232', '1', '40', '5', '45')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь233', '4', '49', '1', '12')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь234', '1', '1', '4', '30')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь235', '2', '22', '5', '44')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь236', '2', '2', '4', '50')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь237', '3', '1', '3', '43')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь238', '4', '18', '1', '22')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь239', '1', '47', '3', '32')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь240', '4', '43', '1', '23')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь241', '2', '46', '3', '10')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь242', '2', '20', '2', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь243', '2', '13', '1', '50')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь244', '1', '24', '2', '34')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь245', '4', '19', '5', '48')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь246', '3', '6', '1', '2')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь247', '1', '42', '1', '33')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь248', '4', '28', '1', '31')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь249', '2', '37', '1', '28')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь250', '2', '8', '2', '30')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь251', '2', '34', '4', '12')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь252', '3', '30', '2', '10')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь253', '1', '3', '2', '32')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь254', '3', '6', '2', '25')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь255', '2', '29', '2', '20')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь256', '4', '43', '3', '11')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь257', '3', '45', '4', '36')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь258', '2', '35', '3', '42')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь259', '1', '11', '3', '2')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь260', '4', '9', '4', '48')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь261', '4', '8', '5', '13')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь262', '3', '0', '1', '23')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь263', '3', '35', '2', '44')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь264', '3', '45', '5', '27')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь265', '2', '29', '2', '11')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь266', '3', '4', '5', '32')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь267', '4', '36', '5', '9')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь268', '2', '32', '2', '34')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь269', '1', '38', '3', '4')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь270', '1', '31', '4', '27')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь271', '1', '15', '5', '8')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь272', '1', '6', '3', '37')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь273', '4', '1', '2', '31')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь274', '2', '19', '4', '45')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь275', '3', '28', '1', '45')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь276', '1', '5', '5', '34')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь277', '2', '26', '5', '38')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь278', '2', '15', '5', '41')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь279', '2', '13', '2', '8')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь280', '3', '4', '5', '1')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь281', '2', '19', '2', '24')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь282', '3', '7', '1', '8')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь283', '1', '29', '5', '31')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь284', '2', '48', '5', '11')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь285', '1', '32', '2', '3')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь286', '4', '45', '4', '28')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь287', '2', '24', '4', '6')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь288', '3', '13', '1', '5')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь289', '1', '12', '3', '7')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь290', '3', '44', '4', '8')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь291', '2', '47', '4', '49')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь292', '2', '49', '5', '48')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь293', '1', '7', '1', '30')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь294', '4', '7', '4', '8')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь295', '1', '15', '4', '42')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь296', '1', '29', '1', '20')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь297', '1', '27', '5', '45')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь298', '4', '46', '3', '31')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь299', '3', '26', '1', '14')
INSERT INTO Component (component_name, component_time, component_quantity, workshop_id, product_id) VALUES('Деталь300', '2', '5', '5', '10')
