INSERT INTO Player (name, height, weight, salary) VALUES('Мина Вячеславович Хохлов', '174', '84', '150000');
INSERT INTO Player (name, height, weight, salary) VALUES('Карпов Аристарх Александрович', '194', '103', '60000');
INSERT INTO Player (name, height, weight, salary) VALUES('Зимин Симон Богданович', '198', '77', '75000');
INSERT INTO Player (name, height, weight, salary) VALUES('Милован Васильевич Лукин', '205', '87', '115000');
INSERT INTO Player (name, height, weight, salary) VALUES('Сила Валерьевич Бобылев', '204', '77', '120000');
INSERT INTO Player (name, height, weight, salary) VALUES('Селезнев Спартак Жанович', '177', '78', '80000');
INSERT INTO Player (name, height, weight, salary) VALUES('Шарапов Ферапонт Харламович', '172', '96', '55000');
INSERT INTO Player (name, height, weight, salary) VALUES('Александров Сила Давыдович', '176', '89', '55000');
INSERT INTO Player (name, height, weight, salary) VALUES('Светозар Георгиевич Елисеев', '187', '79', '70000');
INSERT INTO Player (name, height, weight, salary) VALUES('Марков Ратмир Брониславович', '200', '103', '140000');
INSERT INTO Player (name, height, weight, salary) VALUES('Цветков Боян Елизарович', '186', '106', '140000');
INSERT INTO Player (name, height, weight, salary) VALUES('Воронов Серафим Владиленович', '185', '75', '135000');
INSERT INTO Player (name, height, weight, salary) VALUES('Буров Ерофей Феоктистович', '176', '107', '120000');
INSERT INTO Player (name, height, weight, salary) VALUES('Олимпий Давидович Федоров', '175', '92', '80000');
INSERT INTO Player (name, height, weight, salary) VALUES('Архипов Аверкий Измаилович', '171', '77', '140000');
INSERT INTO Player (name, height, weight, salary) VALUES('Белоусов Нифонт Евсеевич', '209', '100', '145000');
INSERT INTO Player (name, height, weight, salary) VALUES('Ким Феофанович Борисов', '202', '82', '50000');
INSERT INTO Player (name, height, weight, salary) VALUES('Носов Август Димитриевич', '197', '95', '80000');
INSERT INTO Player (name, height, weight, salary) VALUES('Волков Соломон Авдеевич', '204', '80', '150000');
INSERT INTO Player (name, height, weight, salary) VALUES('Аристарх Артемьевич Симонов', '210', '105', '70000');
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (правый)', 'Правша', '45.0', 7);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Защитник (левый)', 'Левша', '46.5', 4);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (левый)', 'Левша', '42.0', 14);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (левый)', 'Левша', '46.0', 19);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (правый)', 'Правша', '45.5', 1);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Защитник (правый)', 'Правша', '45.0', 10);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (левый)', 'Правша', '46.5', 13);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Голкипер', 'Правша', '45.5', 12);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (левый)', 'Правша', '42.5', 8);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Правша', '43.0', 18);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Защитник (правый)', 'Левша', '39.5', 11);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Защитник (правый)', 'Левша', '40.5', 5);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (левый)', 'Левша', '46.0', 9);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Правша', '47.0', 15);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (левый)', 'Левша', '42.0', 20);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Голкипер', 'Левша', '44.0', 16);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Правша', '46.0', 3);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Левша', '44.0', 2);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (правый)', 'Левша', '39.5', 17);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Правша', '46.0', 6);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('42', '83', '4:50', '1:10', 7);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('83', '98', '0:5', '0:40', 20);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('6', '5', '19:55', '0:15', 16);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('45', '84', '14:5', '0:10', 14);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('7', '13', '25:20', '2:15', 19);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('45', '16', '0:50', '2:55', 1);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('91', '77', '13:55', '0:30', 5);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('38', '34', '18:15', '2:55', 13);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('84', '64', '32:5', '2:20', 4);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('27', '14', '28:15', '0:30', 11);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('82', '24', '0:35', '1:20', 9);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('14', '1', '11:30', '0:30', 6);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('72', '97', '6:0', '2:40', 8);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('100', '21', '0:35', '3:5', 15);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('87', '7', '10:25', '0:15', 10);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('35', '38', '11:55', '3:35', 2);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('14', '76', '6:10', '0:10', 3);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('94', '50', '3:55', '1:45', 18);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('16', '78', '21:5', '3:15', 17);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('54', '24', '16:50', '3:40', 12);
