INSERT INTO Player (name, height, weight, salary) VALUES('Соколов Бронислав Владиславович', '180', '100', '55000');
INSERT INTO Player (name, height, weight, salary) VALUES('Павлов Поликарп Ефстафьевич', '170', '83', '145000');
INSERT INTO Player (name, height, weight, salary) VALUES('Сигизмунд Егорович Шилов', '176', '83', '90000');
INSERT INTO Player (name, height, weight, salary) VALUES('Емельянов Изот Якубович', '193', '88', '100000');
INSERT INTO Player (name, height, weight, salary) VALUES('Волков Борис Харлампович', '195', '83', '65000');
INSERT INTO Player (name, height, weight, salary) VALUES('Сидоров Назар Ануфриевич', '210', '95', '80000');
INSERT INTO Player (name, height, weight, salary) VALUES('Волков Фома Измаилович', '179', '91', '80000');
INSERT INTO Player (name, height, weight, salary) VALUES('Богданов Сильвестр Алексеевич', '170', '86', '145000');
INSERT INTO Player (name, height, weight, salary) VALUES('Лукин Нестор Ааронович', '207', '89', '95000');
INSERT INTO Player (name, height, weight, salary) VALUES('Баранов Милен Арсенович', '205', '97', '105000');
INSERT INTO Player (name, height, weight, salary) VALUES('Овчинников Василий Адрианович', '191', '85', '145000');
INSERT INTO Player (name, height, weight, salary) VALUES('Олимпий Юльевич Баранов', '206', '85', '100000');
INSERT INTO Player (name, height, weight, salary) VALUES('Олимпий Аверьянович Стрелков', '183', '93', '55000');
INSERT INTO Player (name, height, weight, salary) VALUES('Клавдий Геннадиевич Бобылев', '205', '110', '60000');
INSERT INTO Player (name, height, weight, salary) VALUES('Михаил Матвеевич Шубин', '210', '86', '85000');
INSERT INTO Player (name, height, weight, salary) VALUES('Виктор Трофимович Доронин', '200', '104', '60000');
INSERT INTO Player (name, height, weight, salary) VALUES('Борис Ааронович Федосеев', '189', '93', '95000');
INSERT INTO Player (name, height, weight, salary) VALUES('Виталий Архипович Карпов', '178', '103', '70000');
INSERT INTO Player (name, height, weight, salary) VALUES('Будимир Ильясович Евсеев', '200', '85', '90000');
INSERT INTO Player (name, height, weight, salary) VALUES('Гурьев Фирс Ефимович', '201', '95', '110000');
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Защитник (левый)', 'Правша', '40.5', 7);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Защитник (правый)', 'Левша', '45.0', 19);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (левый)', 'Правша', '47.5', 12);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (правый)', 'Правша', '40.5', 20);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (левый)', 'Правша', '44.5', 17);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Голкипер', 'Правша', '40.0', 16);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Левша', '42.5', 3);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Правша', '43.5', 9);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Правша', '44.0', 10);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Защитник (правый)', 'Правша', '47.0', 2);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Правша', '40.5', 5);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Левша', '41.5', 14);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Голкипер', 'Правша', '39.0', 18);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (левый)', 'Левша', '47.5', 11);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Защитник (левый)', 'Правша', '47.0', 4);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (правый)', 'Правша', '47.5', 13);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (правый)', 'Правша', '42.0', 15);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Защитник (левый)', 'Правша', '45.5', 1);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (правый)', 'Левша', '43.5', 8);
INSERT INTO Info (position, grip_type, skate_size, player_id) VALUES('Нападающий (центральный)', 'Левша', '42.5', 6);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('6', '73', '23:0', '2:5', 9);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('26', '36', '10:50', '2:10', 18);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('69', '44', '16:35', '1:15', 6);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('50', '80', '9:30', '3:10', 13);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('34', '14', '2:5', '1:50', 4);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('47', '48', '6:15', '3:50', 11);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('0', '98', '2:30', '2:40', 16);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('8', '15', '33:0', '3:30', 17);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('2', '80', '3:35', '1:45', 15);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('89', '53', '15:45', '3:15', 3);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('90', '60', '22:10', '2:15', 12);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('77', '14', '4:55', '0:15', 8);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('4', '54', '22:15', '3:40', 20);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('48', '58', '33:40', '0:10', 5);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('67', '90', '34:5', '3:10', 19);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('39', '65', '12:5', '0:25', 1);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('45', '30', '28:30', '3:25', 10);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('62', '68', '12:5', '3:20', 7);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('58', '88', '19:50', '3:55', 2);
INSERT INTO Stat (goals, assists, playtime, penalty_time, player_id) VALUES('48', '77', '20:40', '0:50', 14);
