INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('ст. Оха', 'ст. Дмитров', '7200', '1080');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('ст. Звенигород', 'клх Плес', '6200', '930');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('к. Щелково', 'к. Алексин', '5200', '780');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Новороссийка', 'клх Юровск', '200', '30');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('д. Калевала', 'ст. Северо-Курильск', '6200', '930');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Оренбург', 'г. Соболево', '5200', '780');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('клх Шаховская', 'к. Кострома', '1700', '255');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('п. Поярково', 'г. Орел', '5700', '855');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Барнаул', 'ст. Махачкала', '1200', '180');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('д. Соловки', 'д. Арсеньев', '7700', '1155');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('клх Сочи', 'к. Терней', '3700', '555');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('ст. Витим', 'ст. Белоярский', '2200', '330');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Усть-Катав', 'д. Нефтекамск', '5700', '855');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('п. Ейск', 'г. Находка', '200', '30');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('ст. Апатиты', 'д. Домбай', '3200', '480');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('д. Кашира', 'ст. Кажим', '6700', '1005');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('п. Архангельск', 'с. Ряжск', '5200', '780');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Калач-на-Дону', 'г. Верхотурье', '1200', '180');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('к. Каргополь', 'д. Белокуриха', '3200', '480');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Асбест', 'к. Тамбей', '1700', '255');
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('KK9506', '1:40:00', '18');
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('UH3390', '10:10:00', '18');
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('QJ4800', '22:40:00', '5');
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('FP0639', '20:20:00', '18');
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('AI3459', '19:00:00', '18');
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('AR6590', '1 day, 9:30:00', '10');
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('NW6889', '1 day, 7:10:00', '14');
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('RS4296', '1 day, 0:40:00', '14');
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('PS3438', '23:00:00', '20');
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('IY7851', '14:20:00', '7');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '59000', 'Earum aliquid molestiae dicta rerum necessitatibus eos. Quae cum optio sunt reiciendis. Dicta voluptatum corporis nulla laboriosam. Dolore animi fugiat rem soluta modi.', '10');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '29000', 'Adipisci cum magnam ad sapiente ipsa laudantium. Occaecati sed delectus.;
Autem asperiores nostrum molestias. Rerum in quod vel in dolores vero. Consectetur sapiente quam fugiat odit.', '9');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '8500', 'Facilis repellat quaerat debitis praesentium. Itaque dolorum fugit repudiandae officiis. Libero perferendis praesentium facilis sint.', '3');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '8000', 'Reprehenderit sed eos fugit iure fugiat excepturi sit. Maiores consectetur vero cumque.;
Distinctio laudantium dolor sint nostrum. Voluptatum illo ab fuga. Veniam corrupti eligendi.', '5');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '18000', 'Fugiat voluptatibus sint beatae doloremque. Nostrum harum ea maiores sunt. Corrupti sunt assumenda aliquam animi beatae. Nulla et quo sunt ullam dolores harum.', '1');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '17000', 'Illum dolore accusantium aut numquam. Necessitatibus voluptate vero cupiditate. Non praesentium iure doloremque vero dolore ullam. Earum officiis rerum laborum.', '3');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '9000', 'Deserunt molestiae commodi quo saepe.', '7');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '79000', 'Neque quia odit autem quam neque consequuntur. Doloribus possimus magnam ut rem veniam tempora consequatur.', '4');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '79000', 'Ipsam quas quas qui ipsa temporibus. Perferendis excepturi voluptates quibusdam. Iste ipsa ea aliquam ipsum.;
Distinctio temporibus impedit officia molestias dolorum. Porro alias provident debitis.', '3');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '21500', 'Facilis in numquam eligendi. Cupiditate voluptates eos.;
Itaque sunt est tenetur. Itaque ad perspiciatis suscipit aspernatur est error.;
Accusamus minus corrupti ducimus nulla culpa.', '5');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '78000', 'Repellendus voluptatum vero id molestias assumenda. Suscipit doloribus dolore eum voluptatem dolorum.', '2');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '11000', 'Recusandae quisquam nemo necessitatibus rem repudiandae. Ullam hic quis. Commodi rerum fugit.;
Totam a expedita rerum id cupiditate dolore.;
Odit itaque alias ea dolore. Atque neque vel corporis.', '4');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '62500', 'Modi recusandae illum dolorum. Totam doloribus aspernatur dolorem ratione. Quas ducimus dolorem consequuntur porro sapiente.', '9');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '10500', 'Modi velit animi impedit repellendus quidem. Ex corrupti a rerum. Inventore fugit rerum quas maxime soluta.', '2');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '70500', 'Quia repudiandae amet voluptate quam unde atque. Consectetur natus aspernatur doloribus fugit magni. Voluptate labore natus sint in reprehenderit error.', '10');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('бизнес', 'Animi in nisi. Ipsam quas deserunt. Eaque iste praesentium rem adipisci.;
Maxime dolor aperiam veritatis recusandae. Optio doloribus nisi consequatur commodi sequi. Accusantium neque sint fugit.', 'для международный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('эконом', 'Illo velit a iusto facere maxime. Cum consectetur id quas.', 'для региональный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('эконом', 'Aut eveniet iure cumque. Vero voluptatem blanditiis accusamus blanditiis optio.;
Minima atque tenetur eaque.', 'для местный протяженности');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Сазонова Таисия Николаевна', 'Кира Егоровна Уварова', 'Владимиров Лев Андреевич', 'Пимен Алексеевич Логинов', 'Трофимов Николай Давидович');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Попов Галактион Феоктистович', 'Колесников Изот Валерьянович', 'Ким Всеволодович Зыков', 'Пономарева Феврония Анатольевна', 'Сорокина Лора Эдуардовна');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Мишина Александра Алексеевна', 'Феврония Юрьевна Соколова', 'Регина Тимуровна Шестакова', 'Вишнякова Лариса Дмитриевна', 'Бронислав Изотович Комиссаров');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Григорьев Сергей Германович', 'Сидорова София Аскольдовна', 'Ершова Олимпиада Робертовна', 'г-н Кондратьев Ладислав Всеволодович', 'Ювеналий Архипович Волков');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Марк Анисимович Сафонов', 'Серафим Богданович Дементьев', 'Моисей Жоресович Колобов', 'Зимин Алексей Артурович', 'Миронов Мечислав Адамович');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Степан Дорофеевич Доронин', 'Артемьева Евдокия Яковлевна', 'Воронова Светлана Борисовна', 'Селиверстов Флорентин Димитриевич', 'Александр Жоресович Крылов');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Князева Любовь Павловна', 'Раиса Ивановна Кудряшова', 'Бронислав Демьянович Тихонов', 'Лукин Борислав Терентьевич', 'Давыдова Фёкла Даниловна');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Таисия Викторовна Рыбакова', 'Ия Андреевна Соловьева', 'Лариса Игоревна Субботина', 'Октябрина Сергеевна Русакова', 'Валерия Рудольфовна Пахомова');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Носков Авксентий Якубович', 'Белоусов Ульян Бориславович', 'Акулина Харитоновна Беспалова', 'Орехова Елизавета Вениаминовна', 'Никифор Гордеевич Куликов');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Герасимов Пантелеймон Анисимович', 'Иосиф Захарьевич Гусев', 'Кириллов Филипп Григорьевич', 'Сорокин Поликарп Афанасьевич', 'Елисеев Януарий Артемьевич');
INSERT INTO Access_plane (crew_id, class_id) VALUES('5', '8');
INSERT INTO Access_plane (crew_id, class_id) VALUES('4', '8');
INSERT INTO Access_plane (crew_id, class_id) VALUES('5', '6');
INSERT INTO Access_plane (crew_id, class_id) VALUES('9', '1');
INSERT INTO Access_plane (crew_id, class_id) VALUES('4', '6');
INSERT INTO Access_plane (crew_id, class_id) VALUES('7', '8');
INSERT INTO Access_plane (crew_id, class_id) VALUES('8', '8');
INSERT INTO Access_plane (crew_id, class_id) VALUES('1', '6');
INSERT INTO Access_plane (crew_id, class_id) VALUES('3', '8');
INSERT INTO Access_plane (crew_id, class_id) VALUES('6', '1');
INSERT INTO Access_plane (crew_id, class_id) VALUES('6', '6');
INSERT INTO Access_plane (crew_id, class_id) VALUES('4', '1');
INSERT INTO Access_plane (crew_id, class_id) VALUES('8', '6');
INSERT INTO Access_plane (crew_id, class_id) VALUES('7', '1');
INSERT INTO Access_plane (crew_id, class_id) VALUES('9', '6');
INSERT INTO Access_plane (crew_id, class_id) VALUES('2', '6');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '1');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '198', '6');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '94', '8');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '176', '1');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '156', '8');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '192', '6');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '156', '8');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '198', '6');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '6');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '6');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '156', '6');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '156', '8');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '198', '6');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '8');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '1');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('13.50 - 01/04/2022', '12.30 - 02/04/2022', '6', 3, '15');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('08.30 - 23/06/2022', '07.30 - 24/06/2022', '2', 9, '3');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('23.40 - 14/12/2021', '22.20 - 15/12/2021', '6', 3, '2');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('03.40 - 01/05/2022', '05.20 - 01/05/2022', '1', 1, '2');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('02.10 - 28/04/2022', '11.40 - 29/04/2022', '7', 6, '2');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('19.30 - 27/03/2022', '02.40 - 29/03/2022', '6', 7, '1');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('14.40 - 11/04/2022', '13.40 - 12/04/2022', '6', 9, '8');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('09.00 - 13/06/2022', '18.30 - 14/06/2022', '10', 6, '7');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('20.00 - 06/05/2022', '03.10 - 08/05/2022', '8', 7, '6');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('16.30 - 05/03/2022', '12.50 - 06/03/2022', '5', 4, '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Красильникова Людмила Викторовна', '6311 283999', 'L36', '14', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Маркова Пелагея Сергеевна', '7215 802427', 'B133', '1', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Агафья Ниловна Федосеева', '3806 954390', 'Z99', '12', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Прасковья Сергеевна Исаева', '4201 147876', 'E130', '15', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Рогова Жанна Леоновна', '2715 539736', 'U59', '4', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Анастасия Вадимовна Терентьева', '7806 277390', 'X86', '14', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Наталья Максимовна Савина', '2718 833949', 'N68', '7', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ольга Афанасьевна Воронова', '0802 089066', 'A106', '12', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Оксана Евгеньевна Кондратьева', '8707 422801', 'K33', '15', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мария Аркадьевна Королева', '8007 244736', 'L149', '3', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Нина Ивановна Ефремова', '7807 252150', 'F132', '7', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Дарья Игоревна Мишина', '1519 763336', 'F74', '1', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мартынов Василий Викторович', '5806 888545', 'F90', '8', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Сидоров Сильвестр Даниилович', '8907 807453', 'M1', '14', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Светлана Вячеславовна Ковалева', '3321 777773', 'L31', '1', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ситникова Иванна Матвеевна', '6818 364317', 'W118', '13', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Сергеев Афанасий Владиславович', '5110 805782', 'A73', '13', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Аполлинарий Валерьевич Волков', '5503 836529', 'X47', '8', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ульян Архипович Фролов', '8719 319947', 'E86', '8', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Соловьев Иннокентий Гавриилович', '6903 850939', 'G110', '1', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Кир Августович Рыбаков', '0304 276181', 'N71', '5', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Михаил Фомич Дементьев', '7705 615666', 'V20', '3', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Игнатов Евлампий Юлианович', '0116 082390', 'A123', '10', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Фомичев Андрон Филимонович', '9915 975783', 'P95', '7', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мясникова Алевтина Руслановна', '2605 792008', 'P61', '13', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Агата Олеговна Горбунова', '9606 553112', 'B122', '1', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мефодий Демьянович Михайлов', '3909 025624', 'L34', '5', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Корнил Викторович Рыбаков', '9610 972354', 'X95', '3', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Капустина Василиса Артемовна', '5817 425228', 'M109', '3', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Афанасьева Агафья Матвеевна', '8202 812782', 'Z32', '8', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Наталья Тимофеевна Гаврилова', '8907 886188', 'Q75', '13', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Зоя Афанасьевна Пестова', '7311 923430', 'D134', '7', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Владимиров Натан Игнатович', '7318 025828', 'N12', '1', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Кулаков Казимир Жоресович', '2304 391724', 'W5', '10', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мария Харитоновна Полякова', '0410 396213', 'H122', '11', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Дроздова Агафья Кузьминична', '3913 729485', 'K149', '15', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Филатова Вероника Вадимовна', '0620 615082', 'U55', '8', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Анисимова Зоя Геннадиевна', '6513 658470', 'E50', '11', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Нинель Валентиновна Алексеева', '0416 000700', 'B23', '10', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Дмитриева Фёкла Макаровна', '1607 563964', 'H28', '12', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Элеонора Васильевна Пестова', '7110 738055', 'S35', '1', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Регина Вячеславовна Цветкова', '1420 580228', 'J58', '2', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Эмилия Святославовна Михайлова', '8911 743691', 'W79', '8', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('тов. Цветкова Евпраксия Харитоновна', '6320 215264', 'R73', '12', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Харитон Григорьевич Щербаков', '5019 117507', 'T42', '9', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Давыдов Ипатий Егорович', '2604 023457', 'M29', '3', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Чеслав Ерофеевич Карпов', '3017 620730', 'L115', '8', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Андрон Адрианович Трофимов', '3004 988530', 'U114', '6', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Горбачева Алла Робертовна', '4514 760869', 'F50', '10', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Устинова Алина Матвеевна', '2210 025083', 'N122', '15', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Гришин Болеслав Антипович', '4913 686824', 'O137', '5', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Евстигней Елисеевич Журавлев', '9103 074607', 'T38', '3', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ипполит Димитриевич Галкин', '5119 356396', 'G55', '1', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Назаров Василий Эдгардович', '9114 600439', 'V70', '12', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Николаева Полина Кирилловна', '2814 173309', 'B13', '3', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Марфа Богдановна Шарапова', '7719 731757', 'U13', '1', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Носкова Кира Петровна', '8709 526986', 'H60', '6', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Олимпиада Вячеславовна Тарасова', '6318 225047', 'Y2', '11', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Виктория Николаевна Мишина', '2320 715735', 'P145', '12', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Акулина Геннадьевна Селиверстова', '0701 561017', 'Z149', '5', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Харлампий Германович Прохоров', '4917 460316', 'V43', '5', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Веселов Фотий Геннадиевич', '8412 184160', 'F67', '7', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Беспалова Вероника Эдуардовна', '8513 009125', 'X3', '11', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Жанна Макаровна Баранова', '5412 816375', 'U142', '11', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Антонова Варвара Яковлевна', '4603 240230', 'T118', '13', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Гурьева Ульяна Эдуардовна', '1518 248273', 'R111', '9', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Анисим Терентьевич Миронов', '1017 405465', 'P79', '9', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Гурьев Капитон Марсович', '0317 084416', 'J49', '8', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Бобылева Вероника Ниловна', '1702 410851', 'F32', '6', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Эмилия Феликсовна Маркова', '5420 162865', 'P127', '4', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Антонова Феврония Олеговна', '5613 141874', 'C73', '5', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Виктория Рубеновна Блинова', '7308 946537', 'V53', '5', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Степанова Александра Михайловна', '8019 084153', 'C55', '9', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Антонова Регина Ивановна', '0314 149372', 'H20', '12', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Исаев Мокей Алексеевич', '2613 683662', 'L85', '8', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Савелий Германович Стрелков', '6606 580539', 'E78', '9', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Милица Ниловна Соловьева', '5614 701831', 'B58', '10', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Маргарита Павловна Федорова', '4209 284822', 'W101', '2', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Белоусова Нонна Максимовна', '1020 344062', 'Y111', '8', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Пономарева Эмилия Леонидовна', '9107 341995', 'K130', '3', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Стрелков Евдоким Дмитриевич', '1208 273613', 'B122', '12', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Антонов Максим Арсенович', '7914 130821', 'S122', '1', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Таисия Рубеновна Тихонова', '3019 647014', 'Q121', '12', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Таисия Аскольдовна Белова', '7421 823081', 'W38', '4', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Николаев Карп Федосеевич', '7711 651617', 'X94', '4', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Третьяков Прокл Власович', '4402 850872', 'J13', '12', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Самсонов Лукьян Адрианович', '6015 495461', 'N113', '12', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Одинцов Ипат Августович', '7207 261566', 'N68', '8', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Панкрат Андреевич Устинов', '8002 339347', 'G4', '10', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Аггей Харламович Ершов', '0913 941319', 'Z108', '10', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Сергеева Полина Станиславовна', '6610 386517', 'Y82', '2', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ольга Яковлевна Мартынова', '7512 052133', 'Z2', '4', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Щукин Спиридон Абрамович', '3120 779433', 'N140', '1', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Натан Зиновьевич Беляев', '0606 417028', 'C95', '14', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Петр Ануфриевич Алексеев', '1711 613144', 'P134', '8', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Валерьян Вячеславович Алексеев', '9512 910139', 'F112', '5', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Владислав Теймуразович Константинов', '4415 004580', 'J141', '7', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Валерьян Ермолаевич Сорокин', '8009 579949', 'R93', '8', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Феликс Геннадиевич Соколов', '4917 926560', 'J21', '15', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Денисов Филарет Юлианович', '4902 728919', 'K145', '6', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Князев Петр Ермолаевич', '2115 435215', 'E131', '9', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Станислав Харлампьевич Харитонов', '6405 293700', 'L3', '6', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Филиппов Валерий Жоресович', '4415 144342', 'U109', '9', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Сергеев Аскольд Вячеславович', '1817 401966', 'D5', '3', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Емельянов Ульян Харламович', '8018 563871', 'W27', '11', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Туров Ефим Витальевич', '3517 054144', 'R32', '1', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Цветкова Регина Богдановна', '0512 719584', 'G91', '10', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Зоя Георгиевна Воронова', '2204 343740', 'V23', '9', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Константинов Изяслав Измаилович', '5707 871284', 'C44', '11', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Леон Адрианович Михеев', '3421 863723', 'G61', '12', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Афиноген Феликсович Иванов', '7118 328635', 'O36', '12', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Баранов Ефрем Ефимович', '9115 493630', 'A70', '6', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Глафира Филипповна Исаева', '3612 190327', 'O84', '5', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Суворова Наталья Юльевна', '9304 825544', 'V51', '8', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Соколов Аристарх Филимонович', '7907 508842', 'G31', '10', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('г-н Агафонов Максимильян Даниилович', '3402 033846', 'C16', '9', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Коновалов Ульян Харлампович', '9505 911449', 'L116', '13', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мариан Валерианович Медведев', '1015 410367', 'N141', '6', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ефимов Август Виленович', '0404 834567', 'Y98', '3', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Стоян Григорьевич Константинов', '5905 201709', 'T117', '7', '3');
