INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('клх Ишим', 'клх Шуя', '2200', '330');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('д. Сочи', 'г. Щелково', '3200', '480');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('клх Касимов', 'п. Новокузнецк', '6200', '930');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('ст. Тулпан', 'п. Петухово', '200', '30');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('г. Листвянка (Иркут.)', 'д. Тихвин', '4700', '705');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('клх Долинск', 'с. Тихорецк', '4200', '630');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('к. Ессентуки', 'г. Оймякон', '2700', '405');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('клх Ярославль', 'с. Смирных', '3700', '555');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('д. Льгов', 'ст. Ижевск', '1200', '180');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('д. Красная Поляна', 'с. Дно', '4700', '705');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Лянтор', 'п. Соловки', '7700', '1155');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Сальск', 'г. Северобайкальск', '3700', '555');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Кызыл', 'д. Ишим', '7700', '1155');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('ст. Суздаль', 'п. Ахтубинск', '700', '105');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Асино', 'ст. Можайск', '4200', '630');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('г. Невинномысск', 'к. Кузнецк', '3700', '555');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('п. Усть-Ишим', 'клх Ступино', '2700', '405');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Переславль-Залесский', 'п. Уфа', '2700', '405');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('г. Избербаш', 'клх Шуя', '1700', '255');
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('клх Павловская', 'г. Ангарск', '200', '30');
INSERT INTO Trip (trip_code, trip_time, trip_name, list_id) VALUES('SO0812', '1 day, 0:40:00', 'Избербаш—Шуя', 19);
INSERT INTO Trip (trip_code, trip_time, trip_name, list_id) VALUES('OG7042', '11:00:00', 'Кызыл—Ишим', 13);
INSERT INTO Trip (trip_code, trip_time, trip_name, list_id) VALUES('JT7564', '17:00:00', 'Павловская—Ангарск', 20);
INSERT INTO Trip (trip_code, trip_time, trip_name, list_id) VALUES('NP5908', '18:40:00', 'Асино—Можайск', 15);
INSERT INTO Trip (trip_code, trip_time, trip_name, list_id) VALUES('DP3256', '8:30:00', 'Ишим—Шуя', 1);
INSERT INTO Trip (trip_code, trip_time, trip_name, list_id) VALUES('FB6001', '10:30:00', 'Усть-Ишим—Ступино', 17);
INSERT INTO Trip (trip_code, trip_time, trip_name, list_id) VALUES('XA6068', '11:50:00', 'Красная—Дно', 10);
INSERT INTO Trip (trip_code, trip_time, trip_name, list_id) VALUES('PG6883', '1 day, 5:40:00', 'Переславль-Залесский—Уфа', 18);
INSERT INTO Trip (trip_code, trip_time, trip_name, list_id) VALUES('BX0461', '6:40:00', 'Листвянка—Тихвин', 5);
INSERT INTO Trip (trip_code, trip_time, trip_name, list_id) VALUES('DN1592', '20:40:00', 'Суздаль—Ахтубинск', 14);
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '26500', 'Fugit minus necessitatibus incidunt doloremque quam.
Molestiae quae consequatur molestiae. Vel itaque cumque voluptatum vitae dolorum similique ratione.', '7');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '25000', 'Dolorem ad fugit consequatur ipsum aliquid laboriosam. Iste soluta dolore eius iste facere. Ducimus ad quidem exercitationem ratione maiores.', '5');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '22000', 'Magnam velit voluptates sint. Molestias quod aliquam tempora earum quibusdam quod. Ad error molestiae veniam. Architecto aspernatur dolores maiores rem.', '2');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '53000', 'Eum eos facere dignissimos perspiciatis reiciendis quo. Neque voluptatum iure beatae minima voluptas asperiores hic.', '5');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '19500', 'Non quos nam modi quos voluptas. Inventore minus quo neque optio. Facilis molestiae doloribus necessitatibus eum assumenda.
Accusamus maiores ducimus molestiae. Nesciunt perferendis quasi.', '5');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '10000', 'Est minus consectetur laudantium fugit sed. Ea error consequuntur recusandae aut. Odit porro possimus ad.', '10');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '19000', 'Voluptatem exercitationem quae nemo corporis. Alias occaecati unde dolorum earum.
Asperiores velit in asperiores dolor quam ipsa voluptas. Delectus iure provident minus in.', '8');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '77000', 'Et reprehenderit harum voluptatum harum perferendis. Tenetur quas itaque inventore adipisci ipsum. Eum nostrum sequi expedita facere neque modi.', '1');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '54000', 'Voluptatibus ipsam perferendis sit dicta. Nihil commodi placeat dolorum perferendis soluta aut et.
Fuga similique voluptate numquam. Quo minima odit quasi.', '5');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '12500', 'Illo maxime modi libero ipsum cum ab. Unde illum assumenda exercitationem. Mollitia quibusdam itaque possimus.', '8');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '64000', 'Ipsa esse excepturi ipsum. Repellendus aperiam magni dolores ipsum corporis.
Earum impedit ad ut porro. Reprehenderit ea adipisci veritatis. Et optio pariatur ipsum.', '7');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '28500', 'Dolor non vitae in iure molestiae.
Quo saepe id. Minima doloribus ipsa nihil aspernatur. Minima numquam saepe impedit sapiente voluptates natus est.', '3');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '68000', 'Perspiciatis dolorem reiciendis voluptates corrupti eligendi maxime. Eos animi et.
Est culpa eaque velit accusantium. Cupiditate beatae temporibus temporibus ab asperiores debitis. Eum sunt dolores.', '7');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '18500', 'Inventore doloremque ipsa molestias. Eius nemo dolorem sit libero.
Odio voluptates temporibus fuga id. Nemo iste veniam quam tenetur doloribus.', '2');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '7500', 'Vitae perspiciatis enim debitis fuga voluptate alias quod. Facilis ab ex explicabo exercitationem.', '4');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '20000', 'Consectetur voluptatem similique saepe placeat dolores. Vero voluptatem praesentium.', '4');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '60500', 'Nesciunt eligendi debitis nisi veritatis delectus quia. Assumenda adipisci ea.
Magnam accusamus ex officia laborum qui. Ipsum dolores ab doloremque nisi sequi.
Dicta deserunt provident quisquam.', '10');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '10000', 'Consectetur voluptatibus minima ipsam facilis. Reiciendis quisquam repellendus delectus non.', '10');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '21000', 'Voluptatum cum eveniet voluptatibus nostrum at laboriosam. Optio facere excepturi iure facere iure. Eveniet nihil quisquam fugiat vero iste autem. Perspiciatis eveniet ex aperiam commodi.', '8');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '5500', 'Nostrum amet architecto repellendus cumque unde temporibus. Voluptatem praesentium nostrum.', '7');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '27000', 'Enim unde quas accusamus aliquid quibusdam. Aliquid soluta beatae necessitatibus fugit atque quas velit. Quidem placeat harum repellat animi non.', '9');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '67000', 'Optio maxime perspiciatis.
Officia quas tenetur deleniti autem possimus aut. Sunt soluta eos iure voluptate.', '10');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '58500', 'Amet odio alias voluptate facere iste eveniet. Sit excepturi quasi libero.
Odio exercitationem maxime expedita alias consequuntur. Facere quam officiis incidunt perferendis maiores.', '6');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '12500', 'Nobis officiis nulla quam soluta. Delectus voluptatem harum inventore ad ipsum officia possimus. Dicta tempora expedita. Pariatur explicabo voluptate saepe consectetur.', '1');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '21500', 'Perferendis cupiditate exercitationem mollitia error vitae sunt. Rerum dolorum quis iusto. Autem voluptates provident facilis possimus iste.', '9');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '52500', 'Eos fugiat possimus. Nam doloribus id sed.
Expedita animi rerum. Ab eligendi ea.
Commodi officia dignissimos voluptate. Nesciunt pariatur officia aperiam. Nam iusto rerum minima in.', '9');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '17500', 'Aspernatur dicta voluptatem enim debitis nulla. Sapiente deserunt ullam ipsam. Aspernatur autem odio.', '9');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '29000', 'Hic adipisci fuga nesciunt. Similique ab eveniet. Exercitationem rem sapiente corrupti pariatur eius soluta. Porro ut sit eveniet deserunt.', '2');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '23000', 'Expedita harum cupiditate minima molestias. Sequi mollitia autem corporis aperiam. Vitae expedita molestiae iure. Aperiam sequi architecto.', '2');
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '57000', 'Reiciendis maiores nihil maiores. Cum est quaerat harum atque.', '1');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('эконом', 'Dolor praesentium cumque praesentium eligendi officia sequi. Error dolorum nisi rem nobis nam. Repellendus molestiae suscipit ullam deserunt quas.
Quos incidunt placeat dolores fugiat sunt possimus.', 'для местный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('бизнес', 'Necessitatibus placeat fugiat eius. Officiis repellat doloremque consequatur. Porro magnam qui illum laborum libero iste. Facere autem officiis ea doloremque natus.', 'для местный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('бизнес', 'Sint maxime numquam laudantium perspiciatis quas non. Quas eum voluptates omnis quaerat. Architecto tempora impedit culpa facilis reiciendis.', 'для местный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('бизнес', 'Cum commodi beatae.
Ullam hic ex ad impedit enim debitis. Quisquam accusamus necessitatibus provident libero provident. Nisi ullam fugit neque quisquam.', 'для региональный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('первый', 'Odit ipsa quis sit nam rerum repudiandae fuga. Maiores voluptatibus fugit vitae officia veritatis. Cupiditate voluptatem minima animi repudiandae.', 'для местный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('эконом', 'Distinctio ipsum architecto. Magnam ipsa ratione rem excepturi nostrum dolorem tempore. Atque est possimus perspiciatis.', 'для местный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('первый', 'Sed voluptas fugiat odit exercitationem quasi officiis. Earum expedita repellat suscipit dolorum voluptate consequuntur quisquam.
Voluptas consectetur nemo necessitatibus non numquam dolor nemo.', 'для международный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('бизнес', 'Repellat ipsam dolorum amet cumque quidem. Neque qui quidem minus dolorem eos harum illum. Consequuntur voluptates hic perspiciatis.', 'для местный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('бизнес', 'Possimus natus eius et atque animi repellendus. Saepe voluptates dolorum eum doloremque. Laudantium sequi reiciendis quibusdam minus assumenda similique.', 'для местный протяженности');
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('первый', 'Fugit totam odio tempora dolor nesciunt. Unde quidem cumque consequuntur officia aperiam.
Aperiam inventore inventore veritatis. Eius quas sint.
A quod voluptatem totam. Ab illum natus placeat neque.', 'для местный протяженности');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3, crew_level) VALUES('Белякова Таисия Валериевна', 'Маркова Нинель Филипповна', 'Вениамин Аверьянович Зыков', 'Исаев Юлиан Изотович', 'Милица Григорьевна Хохлова', '3');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3, crew_level) VALUES('Виноградова Лариса Дмитриевна', 'Амос Гордеевич Костин', 'Кабанов Парфен Филиппович', 'Дьячкова Анастасия Петровна', 'Моисеева Фаина Макаровна', '3');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3, crew_level) VALUES('Борис Ермолаевич Иванов', 'Федотов Аверкий Ильич', 'Маргарита Рудольфовна Тетерина', 'Анастасия Игоревна Кондратьева', 'Ия Георгиевна Русакова', '1');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3, crew_level) VALUES('Уварова Надежда Леоновна', 'г-н Романов Ермил Марсович', 'Мирослав Демидович Сорокин', 'Полякова Тамара Львовна', 'Боброва Антонина Валериевна', '2');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3, crew_level) VALUES('Захаров Мир Брониславович', 'Ковалев Викторин Феоктистович', 'Элеонора Тимофеевна Боброва', 'Тихонова Надежда Эдуардовна', 'Агафонова Клавдия Вячеславовна', '1');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3, crew_level) VALUES('Комарова Фаина Альбертовна', 'Фаина Ждановна Козлова', 'Феврония Владиславовна Богданова', 'Лидия Геннадьевна Николаева', 'Юлия Архиповна Одинцова', '2');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3, crew_level) VALUES('Силин Якуб Даниилович', 'Самойлов Иосиф Тарасович', 'Надежда Даниловна Крюкова', 'Тамара Леонидовна Лобанова', 'Лукия Тарасовна Ермакова', '2');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3, crew_level) VALUES('Глафира Захаровна Фокина', 'Валентина Семеновна Савельева', 'Гусева Иванна Афанасьевна', 'Шилов Филарет Ефимьевич', 'Яков Андреевич Куликов', '3');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3, crew_level) VALUES('Крюкова Ульяна Архиповна', 'Людмила Владимировна Попова', 'Фома Аксёнович Муравьев', 'Яковлев Изяслав Егорович', 'Захар Дмитриевич Лазарев', '2');
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3, crew_level) VALUES('Никодим Филиппович Федосеев', 'Маслов Трофим Викторович', 'Муравьев Владислав Исидорович', 'Голубева Евфросиния Антоновна', 'Костина Олимпиада Ниловна', '3');
INSERT INTO Access_plane (crew_id, class_id) VALUES('5', '3');
INSERT INTO Access_plane (crew_id, class_id) VALUES('2', '9');
INSERT INTO Access_plane (crew_id, class_id) VALUES('6', '5');
INSERT INTO Access_plane (crew_id, class_id) VALUES('10', '6');
INSERT INTO Access_plane (crew_id, class_id) VALUES('7', '10');
INSERT INTO Access_plane (crew_id, class_id) VALUES('4', '10');
INSERT INTO Access_plane (crew_id, class_id) VALUES('7', '9');
INSERT INTO Access_plane (crew_id, class_id) VALUES('10', '9');
INSERT INTO Access_plane (crew_id, class_id) VALUES('9', '1');
INSERT INTO Access_plane (crew_id, class_id) VALUES('3', '3');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '2');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '93', '1');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '189', '7');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '198', '9');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '82', '9');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '139', '10');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '198', '2');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '9');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '198', '7');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '9');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '198', '2');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '156', '10');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '154', '2');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '155', '5');
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '86', '9');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('2021-12-20 23:40', '2021-12-21 20:20', '4', 10, '10');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('2021-10-05 13:30', '2021-10-06 06:30', '7', 3, '2');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('2022-01-16 21:50', '2022-01-17 18:30', '7', 10, '6');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('2022-06-16 18:00', '2022-06-17 02:30', '6', 5, '4');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('2021-11-07 19:40', '2021-11-08 12:40', '3', 3, '15');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('2021-11-01 08:30', '2021-11-01 15:10', '9', 9, '7');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('2022-06-06 14:30', '2022-06-07 07:30', '9', 3, '13');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('2021-12-20 09:30', '2021-12-21 06:10', '10', 10, '10');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('2022-02-13 04:20', '2022-02-13 15:20', '2', 2, '15');
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('2022-04-02 13:10', '2022-04-03 01:00', '6', 7, '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Родионов Юлий Дорофеевич', '9213 101394', 'N41', '27', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Соловьев Тихон Григорьевич', '1409 216171', 'B5', '15', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Федосий Вячеславович Кузьмин', '6210 746596', 'C109', '14', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Борисов Всемил Исидорович', '7307 595243', 'I2', '10', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Вера Матвеевна Мамонтова', '5310 363152', 'Y5', '9', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Кириллова Олимпиада Ждановна', '9413 728917', 'O63', '24', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Михей Эдуардович Александров', '8312 022157', 'K110', '9', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Попов Творимир Филиппович', '7216 398830', 'T96', '28', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Третьяков Софон Аксёнович', '6007 879842', 'S65', '18', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Гаврила Иосипович Артемьев', '7718 723870', 'J1', '30', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Маргарита Федоровна Александрова', '3907 618443', 'W66', '27', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Бирюкова Екатерина Борисовна', '8315 663575', 'W41', '4', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Алла Филипповна Третьякова', '1813 824004', 'K86', '7', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Самсонова Регина Аскольдовна', '3709 961361', 'S70', '17', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Фомичева Агафья Юрьевна', '9906 666148', 'C99', '18', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Авдеева Анжела Болеславовна', '3320 891753', 'E4', '24', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Жукова Виктория Константиновна', '4015 753272', 'M62', '25', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Лора Анатольевна Давыдова', '2605 510319', 'G77', '11', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Титов Святослав Валентинович', '5020 784621', 'Y12', '24', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Макаров Назар Гаврилович', '2307 016386', 'H83', '24', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Зайцева Елизавета Захаровна', '9817 821934', 'X54', '12', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Галкина Пелагея Максимовна', '6608 920632', 'K114', '29', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Калашникова Елена Филипповна', '3503 735554', 'V37', '18', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Лидия Анатольевна Емельянова', '1717 386665', 'C71', '3', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Кабанов Панфил Артемьевич', '2609 824321', 'C66', '19', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Исай Валерианович Третьяков', '1121 645514', 'D105', '26', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Лукина Вероника Никифоровна', '9120 033929', 'U127', '29', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Агафья Станиславовна Дементьева', '8912 369528', 'O109', '14', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Октябрина Натановна Виноградова', '3701 948359', 'B87', '6', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Олимпиада Никифоровна Уварова', '6011 016383', 'G66', '8', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Тихон Ефремович Данилов', '5608 094568', 'E35', '22', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Болеслав Григорьевич Зимин', '4612 356271', 'T9', '2', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Жуков Юрий Валерьянович', '0901 621213', 'D110', '20', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Зосима Жанович Елисеев', '9508 443410', 'O25', '12', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Маргарита Болеславовна Шестакова', '5602 587001', 'O114', '7', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Брагина Татьяна Ниловна', '6217 729314', 'G62', '14', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Милица Николаевна Сафонова', '7418 198257', 'E80', '1', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Глафира Кузьминична Петрова', '4921 615237', 'P27', '30', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Максимова Зоя Федоровна', '2617 554234', 'K34', '8', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Гусева Раиса Яковлевна', '0806 664612', 'F135', '14', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Белозерова Фёкла Борисовна', '0602 011423', 'Q61', '3', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Жукова Светлана Харитоновна', '8606 255071', 'K123', '11', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Голубева Нина Васильевна', '4921 297210', 'R140', '14', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Власова Клавдия Даниловна', '4412 785851', 'A27', '1', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Надежда Эдуардовна Шестакова', '7615 425504', 'I115', '24', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Дарья Архиповна Горбачева', '4120 437733', 'D14', '29', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Аркадий Тихонович Сорокин', '7602 855317', 'R75', '28', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Тихон Иосифович Егоров', '6303 024107', 'L105', '1', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Орлов Михей Игоревич', '9707 875616', 'W126', '25', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Агап Андреевич Архипов', '9401 255382', 'Z45', '5', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Терентьева Евпраксия Петровна', '5919 684414', 'T40', '8', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Юлия Валентиновна Мухина', '8010 951517', 'W25', '21', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Светозар Бенедиктович Дементьев', '2112 153819', 'Z143', '21', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Евлампий Харлампович Макаров', '3613 702926', 'N141', '20', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Фотий Брониславович Захаров', '2015 065246', 'J72', '4', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мстислав Харламович Виноградов', '6519 057075', 'I8', '16', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Зосима Изотович Ковалев', '6001 362361', 'Z95', '25', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Артемьев Клавдий Вилорович', '3804 509331', 'I56', '23', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Семен Ефимович Ширяев', '7915 652932', 'R57', '25', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Шарапов Севастьян Измаилович', '1721 559214', 'T83', '20', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Бирюкова Олимпиада Юльевна', '9811 069345', 'C112', '20', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ирина Ниловна Сорокина', '0517 476338', 'N22', '28', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('тов. Ильина Лидия Юльевна', '0417 987770', 'L65', '5', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Коновалова Надежда Владиславовна', '0405 533245', 'N148', '26', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('тов. Емельянов Юлиан Игоревич', '8814 220803', 'J64', '8', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Твердислав Глебович Ефимов', '5808 081868', 'I145', '9', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Васильев Юрий Ефимьевич', '4606 274738', 'C119', '18', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Панкрат Изотович Ермаков', '6519 581077', 'U80', '16', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Вишнякова Валерия Харитоновна', '4220 675419', 'L116', '4', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Жукова Вера Яковлевна', '8909 955989', 'L22', '14', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Алевтина Игоревна Макарова', '0607 975453', 'V134', '11', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Дарья Георгиевна Блинова', '7811 338998', 'L24', '18', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Остап Терентьевич Фокин', '9506 079819', 'M66', '4', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ювеналий Иларионович Медведев', '0918 750027', 'J32', '9', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Велимир Анисимович Шаров', '5209 312322', 'T80', '3', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Вениамин Фадеевич Голубев', '9114 893428', 'K134', '19', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Григорьева Валерия Егоровна', '8315 252877', 'D118', '25', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Тарасова Людмила Геннадьевна', '6708 747110', 'M39', '26', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Антип Вячеславович Никифоров', '7907 551750', 'Y93', '25', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Аполлинарий Трофимович Морозов', '6510 096633', 'D34', '30', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Агата Ивановна Баранова', '8503 440034', 'W6', '2', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Афанасьева Феврония Аскольдовна', '7715 644715', 'K142', '14', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Терентьева Ирина Дмитриевна', '1916 188731', 'T98', '28', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Анжелика Харитоновна Калашникова', '7715 233171', 'Q81', '19', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Марина Вениаминовна Дорофеева', '3615 392224', 'C41', '22', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Евпраксия Артемовна Сорокина', '0516 076339', 'E74', '26', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Муравьев Велимир Геннадиевич', '9608 505702', 'O69', '13', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Клавдий Даниилович Федотов', '5014 173011', 'S40', '7', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Антонина Валериевна Герасимова', '4819 241949', 'L6', '13', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Кира Валериевна Тетерина', '2516 210687', 'Q51', '6', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('тов. Бирюков Елисей Дмитриевич', '5703 638777', 'O4', '23', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Лазарев Бажен Афанасьевич', '0908 541467', 'X94', '28', '9');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мишин Святослав Глебович', '4804 297368', 'B48', '20', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ираклий Гертрудович Рябов', '0905 393890', 'I59', '7', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Громова Зинаида Федоровна', '3907 992311', 'Y129', '9', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Дорофеева Феврония Геннадьевна', '4515 370570', 'U103', '24', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Родион Филиппович Кабанов', '0315 447929', 'G150', '15', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Наумов Кирилл Фокич', '9120 878861', 'Q105', '12', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Семенова Анжелика Мироновна', '5801 263882', 'I63', '20', '5');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Шарапова Алина Константиновна', '4904 223189', 'S56', '26', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ефим Владиленович Горшков', '4012 276700', 'U93', '24', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Орлов Аникита Давыдович', '5812 216778', 'B36', '9', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Жанна Борисовна Одинцова', '3407 339617', 'C84', '14', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Дроздова Надежда Викторовна', '1813 264769', 'L96', '24', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Михей Дмитриевич Колобов', '9109 491132', 'P70', '21', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ян Гурьевич Мишин', '1005 248818', 'D147', '9', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Селиверст Игнатьевич Бобров', '5218 141269', 'B8', '24', '4');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мстислав Арсеньевич Панов', '0411 306962', 'A82', '30', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Беляев Ульян Фокич', '3916 315653', 'F72', '9', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Денис Анатольевич Кабанов', '6618 180441', 'M142', '6', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Анжелика Ефимовна Королева', '2015 682822', 'B54', '24', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Филиппова София Вадимовна', '7721 197080', 'K68', '3', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Кулаков Ефрем Теймуразович', '5211 909879', 'Z40', '18', '10');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Куликов Аверкий Еремеевич', '6511 484883', 'S40', '15', '3');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Алевтина Рубеновна Комарова', '0917 283271', 'Q119', '25', '7');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Маргарита Юрьевна Быкова', '5611 792389', 'L136', '2', '6');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Таисия Евгеньевна Герасимова', '2912 259504', 'W42', '12', '1');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Игнатьева София Рубеновна', '1721 564788', 'J24', '13', '2');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Гущин Станимир Давыдович', '4421 135833', 'F76', '20', '8');
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Архип Александрович Панфилов', '7304 919170', 'W18', '20', '3');
