INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Ижевск', 'г. Баргузин', '5700', '855')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('д. Чехов', 'с. Ведено', '6200', '930')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('клх Тотьма', 'к. Галич', '4200', '630')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('г. Старый Оскол', 'с. Кулунда', '7200', '1080')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('п. Усинск', 'г. Чермоз', '4200', '630')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('п. Оймякон', 'с. Кетченеры', '5700', '855')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('ст. Билибино', 'с. Миллерово', '200', '30')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('п. Хоста', 'п. Павловская', '4700', '705')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('клх Красноселькуп', 'ст. Абинск', '7700', '1155')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Гремячинск (Бурят.)', 'г. Карабудахкент', '4200', '630')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('п. Тура', 'к. Красноселькуп', '5700', '855')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('г. Североморск', 'д. Инта', '3200', '480')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('к. Кисловодск', 'клх Лабытнанги', '7200', '1080')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('ст. Миасс', 'г. Салехард', '4700', '705')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('п. Белореченск', 'д. Териберка', '4700', '705')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('г. Качканар', 'д. Черусти', '7200', '1080')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('к. Адлер', 'д. Домбай', '1200', '180')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('г. Гатчина', 'с. Элиста', '700', '105')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('с. Карачаевск', 'п. Горячинск', '7200', '1080')
INSERT INTO List (list_departure, list_arrive, list_length, list_fuel) VALUES('д. Набережные Челны', 'п. Анапа', '3200', '480')
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('ME5809', '23:10:00', '15')
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('UB4880', '14:50:00', '13')
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('IJ9918', '14:00:00', '10')
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('TG6907', '1 day, 10:10:00', '16')
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('CG2207', '8:40:00', '7')
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('HT5609', '1:10:00', '9')
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('WI0437', '8:00:00', '6')
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('CC6204', '17:40:00', '17')
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('OS6724', '1 day, 8:20:00', '2')
INSERT INTO Trip (trip_code, trip_time, list_id) VALUES('MC2304', '1 day, 9:30:00', '3')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '23000', 'Quam repudiandae id fuga ipsam. Odit tempore consequatur sequi fugit mollitia. Eligendi cupiditate nam amet sed occaecati tenetur.
Consectetur cupiditate magni voluptatibus. Sapiente numquam quas.', '10')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '57000', 'Deserunt velit necessitatibus dolorem consequatur. Facere aliquam aspernatur adipisci maxime in distinctio eligendi.', '3')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '63000', 'Blanditiis voluptates possimus quaerat id veniam. Asperiores voluptate quo.', '6')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '7500', 'Cupiditate inventore modi quos eveniet. In modi vel amet incidunt. Cupiditate error expedita.
Dignissimos eaque ducimus nulla rerum voluptatum cupiditate. Dolores quis fuga voluptas.', '4')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '77000', 'Veritatis ullam consectetur esse deleniti accusamus officiis. Pariatur ex nemo velit nobis repellendus.
Occaecati voluptatibus commodi cumque id aliquid. Consequuntur earum odit neque.', '8')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '64500', 'Itaque ipsa modi aperiam dolorem.
Accusantium quaerat tenetur culpa. Atque unde deserunt odio laboriosam similique incidunt. Asperiores mollitia assumenda laudantium.', '3')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '71000', 'Quisquam ullam harum ipsam enim molestias explicabo. Aspernatur dicta aperiam distinctio asperiores. Sequi sed culpa repellat.', '5')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '9000', 'Asperiores deserunt dignissimos exercitationem. Sit nostrum provident natus fugit fuga.', '5')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '17000', 'Numquam animi dolore fuga deleniti consequuntur.
Facere veritatis odit cupiditate dignissimos officiis. Eius perferendis dolor voluptatem dolore quam.', '4')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '75000', 'Tempore rem itaque cupiditate ab iusto neque. Rerum eius accusantium dignissimos fugiat.', '9')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '21500', 'Reprehenderit saepe tempore quidem sit. Blanditiis mollitia suscipit.
Alias amet minima expedita doloribus.', '4')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '23000', 'Hic deleniti aliquam vel. Incidunt molestias deleniti magni.
Ullam repellat sequi ipsam suscipit eius.
Voluptas animi culpa ab nesciunt. Assumenda sequi excepturi ab non cum non.', '8')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('комфорт', '29000', 'Possimus dolore consequuntur molestiae. Minima explicabo voluptates voluptas quaerat nihil nam. Ipsum itaque soluta reprehenderit. Accusantium recusandae sapiente minus harum maxime ex.', '3')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('бизнес', '52000', 'Veritatis minus molestiae illo.
Commodi cupiditate cupiditate rem aut incidunt. Inventore voluptates dolorum eligendi laboriosam nemo possimus aspernatur. Assumenda magnam repellat dolorem.', '4')
INSERT INTO Price (price_rate, price_cost, price_summary, trip_id) VALUES('эконом', '4500', 'Quasi sequi praesentium qui voluptatem vitae at magnam. Repudiandae quaerat sunt quasi numquam quis ab.
Rerum saepe fugit ut officiis. Dignissimos iusto enim ex.', '10')
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('эконом', 'Perspiciatis autem enim facilis maxime repellat occaecati. Quos rerum ullam tempora tempore rerum.', 'для местный протяженности')
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('бизнес', 'Illum facere quisquam quia. Doloribus doloribus iusto reprehenderit ex.
Rerum assumenda corrupti. Dolorem debitis placeat assumenda possimus. Ipsa vero voluptatibus.', 'для местный протяженности')
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('первый', 'Dignissimos beatae aliquid quaerat voluptate praesentium earum ad. Modi accusantium id et est itaque.
Doloribus provident quam minus eos sint natus.', 'для местный протяженности')
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('бизнес', 'Voluptate nihil molestias nesciunt quo. Velit illo quas quae nihil. Quasi velit possimus quasi sapiente.', 'для региональный протяженности')
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('бизнес', 'Quam aspernatur facilis fugiat. Ipsa consectetur sint. Tempore magnam veritatis ad.
Est ipsam sint iure magnam voluptate saepe. Autem laborum qui repellendus. Nihil laudantium vel recusandae dolorem.', 'для местный протяженности')
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('эконом', 'Adipisci officiis autem praesentium iure. Non harum fugiat unde ea. Eos earum excepturi placeat repudiandae.', 'для международный протяженности')
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('первый', 'Cupiditate at a saepe qui a.
Fugiat cumque ex alias quidem quasi velit eaque. Sint laborum est nobis repellat unde repellat eaque.', 'для региональный протяженности')
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('первый', 'Quidem ipsum in vitae eos. Perferendis veniam corporis nemo.
Error commodi veritatis temporibus. Quaerat esse in fugit.', 'для местный протяженности')
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('первый', 'Quis mollitia ab. Iusto omnis illo placeat omnis provident et. Quae occaecati sint distinctio nostrum. Magnam enim perspiciatis aut ad quidem pariatur assumenda.', 'для международный протяженности')
INSERT INTO Class (class_classif, class_summary, class_type) VALUES('первый', 'Odio doloremque consequuntur repellendus quia hic laborum. Vero nihil vitae debitis. Amet nostrum odit saepe.', 'для местный протяженности')
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Ольга Васильевна Терентьева', 'Анжелика Харитоновна Лихачева', 'Турова Светлана Юльевна', 'Лора Петровна Ильина', 'Агата Ивановна Савина')
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Васильева Нинель Святославовна', 'Галина Архиповна Ларионова', 'Алина Вадимовна Котова', 'Екатерина Владимировна Крылова', 'Игнатова Синклитикия Тимофеевна')
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Гурий Исидорович Носов', 'Панов Осип Геннадиевич', 'Нинель Григорьевна Князева', 'Ангелина Наумовна Архипова', 'Красильникова Нина Юрьевна')
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Савина Ангелина Константиновна', 'Адриан Авдеевич Ларионов', 'Казаков Капитон Юлианович', 'Рябова Марфа Ильинична', 'Ирина Афанасьевна Воронцова')
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Лавр Анатольевич Агафонов', 'Ферапонт Ааронович Кононов', 'Анжелика Сергеевна Колобова', 'Колесникова Марина Валериевна', 'Евдоким Харлампьевич Кулагин')
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('тов. Щербаков Софон Филиппович', 'Акулина Кирилловна Федорова', 'Силина Евдокия Николаевна', 'Эммануил Валентинович Орлов', 'Мокей Валерьевич Рожков')
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Амвросий Всеволодович Ефимов', 'Софрон Феофанович Костин', 'Фокина Анжелика Георгиевна', 'Антонина Вениаминовна Соловьева', 'Данилова Елена Дмитриевна')
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Оксана Валентиновна Фролова', 'Ким Филиппович Захаров', 'Роман Марсович Назаров', 'Авдей Матвеевич Прохоров', 'Тимофей Эдгардович Шубин')
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Анастасия Станиславовна Копылова', 'Алексеева Людмила Матвеевна', 'Ксения Вадимовна Маркова', 'Котова Екатерина Ждановна', 'Романов Артем Августович')
INSERT INTO Crew (crew_captian, crew_navigator, crew_steward1, crew_steward2, crew_steward3) VALUES('Рогов Остап Богданович', 'Морозова Фёкла Юльевна', 'Сафонова Дарья Григорьевна', 'Анжела Владимировна Кошелева', 'Иванна Тарасовна Дмитриева')
INSERT INTO Access_plane (crew_id, class_id) VALUES('6', '9')
INSERT INTO Access_plane (crew_id, class_id) VALUES('7', '6')
INSERT INTO Access_plane (crew_id, class_id) VALUES('4', '8')
INSERT INTO Access_plane (crew_id, class_id) VALUES('5', '4')
INSERT INTO Access_plane (crew_id, class_id) VALUES('1', '8')
INSERT INTO Access_plane (crew_id, class_id) VALUES('1', '9')
INSERT INTO Access_plane (crew_id, class_id) VALUES('1', '2')
INSERT INTO Access_plane (crew_id, class_id) VALUES('5', '10')
INSERT INTO Access_plane (crew_id, class_id) VALUES('10', '6')
INSERT INTO Access_plane (crew_id, class_id) VALUES('5', '5')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '1')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '154', '10')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '198', '7')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '156', '8')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '153', '9')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '88', '1')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '198', '7')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '5')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '156', '1')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('большой', '198', '10')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '156', '7')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '5')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('средней', '156', '9')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '9')
INSERT INTO Plane (plane_type, plane_places, class_id) VALUES('малой', '96', '10')
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('02.20 - 10/02/2022', '11.00 - 10/02/2022', '3', 5, '9')
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('12.10 - 18/03/2022', '11.20 - 19/03/2022', '3', 1, '10')
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('14.50 - 26/04/2022', '08.30 - 27/04/2022', '10', 8, '6')
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('11.50 - 12/11/2021', '11.00 - 13/11/2021', '1', 1, '12')
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('05.50 - 29/10/2021', '19.50 - 29/10/2021', '7', 3, '12')
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('11.50 - 07/06/2022', '05.30 - 08/06/2022', '10', 8, '13')
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('02.00 - 30/10/2021', '10.00 - 30/10/2021', '4', 7, '5')
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('07.40 - 30/10/2021', '21.40 - 30/10/2021', '10', 3, '8')
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('07.00 - 09/10/2021', '15.40 - 09/10/2021', '6', 5, '4')
INSERT INTO Flight (flight_departure, flight_arrive, crew_id, trip_id, plane_id) VALUES('19.30 - 04/12/2021', '09.30 - 05/12/2021', '3', 3, '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Селиверст Харитонович Никитин', '4612 038406', 'L44', '3', '2')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Воронцов Любим Викторович', '5214 281534', 'V83', '15', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Боброва Наталья Альбертовна', '9508 429763', 'E107', '5', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Агафья Сергеевна Дементьева', '6918 228753', 'Y106', '6', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ираида Романовна Богданова', '7221 550331', 'Z131', '10', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Полина Геннадиевна Ефимова', '6317 715074', 'K92', '7', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Регина Семеновна Меркушева', '5106 797385', 'X96', '2', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Жанна Святославовна Блинова', '0511 777146', 'B15', '4', '3')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Наталья Валентиновна Костина', '5808 112290', 'A62', '6', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Олимпиада Харитоновна Елисеева', '9318 790600', 'U126', '5', '2')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Третьяков Ким Измаилович', '8906 333245', 'T31', '7', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Федот Авдеевич Жуков', '0802 929322', 'S18', '6', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Светлана Ильинична Александрова', '6415 254714', 'V34', '15', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Филиппова Ксения Натановна', '6015 694474', 'Z25', '7', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Жуков Епифан Фёдорович', '4206 839663', 'A77', '12', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Громов Николай Терентьевич', '7207 214741', 'Y90', '13', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Роман Игнатьевич Пахомов', '6410 178858', 'L124', '15', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Рожков Константин Трофимович', '0415 352311', 'T1', '14', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Эмиль Абрамович Степанов', '8920 834207', 'P60', '1', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Максимильян Гаврилович Волков', '3408 417457', 'H24', '15', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Марков Зосима Васильевич', '6218 954201', 'W122', '15', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ларионов Прохор Теймуразович', '6417 040825', 'I107', '8', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ипатий Эдуардович Исаков', '5310 784279', 'M143', '4', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Блинов Афиноген Тарасович', '0209 155063', 'R72', '1', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Комаров Твердислав Ильясович', '7712 876880', 'I120', '10', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Крылов Валерий Марсович', '1611 563343', 'E99', '11', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Зимин Аристарх Адрианович', '0402 644026', 'Q97', '8', '3')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('тов. Захаров Мечислав Венедиктович', '5516 685881', 'L44', '2', '9')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Комаров Василий Валентинович', '1311 013997', 'A59', '9', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ладислав Адамович Дмитриев', '8718 929388', 'W132', '2', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мартьян Теймуразович Ширяев', '3611 437429', 'M127', '15', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Кузнецов Изот Тарасович', '9410 229241', 'V115', '5', '9')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Тимофей Валерианович Кузьмин', '2207 320113', 'R47', '12', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Рябов Иосиф Григорьевич', '8010 671418', 'M42', '4', '2')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Буров Эмиль Игнатьевич', '2211 260375', 'W134', '8', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Бажен Измаилович Щербаков', '6705 339872', 'S46', '8', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Лобанова Прасковья Антоновна', '7903 383372', 'E49', '6', '3')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('г-жа Ларионова Нинель Натановна', '0602 826006', 'B144', '14', '9')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ия Тимуровна Киселева', '5621 878363', 'T110', '13', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Олимпиада Аркадьевна Емельянова', '5002 434634', 'P78', '6', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Наркис Геннадиевич Журавлев', '3204 191393', 'C89', '13', '3')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Фомичев Соломон Владиленович', '7212 994478', 'K139', '4', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Горбачев Кирилл Анатольевич', '8519 922574', 'A72', '15', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Лихачев Никита Егорович', '4808 466819', 'T142', '11', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Галина Евгеньевна Комиссарова', '4016 125704', 'Q37', '14', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Любовь Вениаминовна Панова', '2218 015672', 'L49', '13', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Осипова Алевтина Мироновна', '1018 553979', 'I76', '3', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Варвара Георгиевна Родионова', '0604 006440', 'U91', '13', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Сафонов Климент Измаилович', '0407 821514', 'D131', '14', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Сорокин Боян Бенедиктович', '6621 534996', 'B7', '3', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Венедикт Аверьянович Ильин', '3121 287079', 'R40', '14', '9')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Бажен Эдгарович Дроздов', '9803 383252', 'F80', '5', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Яковлев Артемий Игоревич', '6901 857925', 'M12', '13', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Тарас Ануфриевич Виноградов', '5303 700688', 'Z77', '5', '2')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Мухина Маргарита Архиповна', '0919 855340', 'N131', '14', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ульяна Станиславовна Суханова', '1216 887121', 'C16', '14', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Зиновьева Лидия Андреевна', '1021 476553', 'H49', '15', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Селезнева Ия Макаровна', '6817 985413', 'S128', '12', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Тамара Святославовна Кузнецова', '6812 278209', 'S125', '4', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Глафира Дмитриевна Дьячкова', '8819 754170', 'I19', '5', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Карпов Ратибор Феофанович', '2003 777396', 'O132', '14', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Бажен Харитонович Алексеев', '0512 994518', 'L2', '1', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Октябрина Валериевна Авдеева', '6813 212191', 'K117', '15', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Тамара Аскольдовна Рожкова', '1419 372420', 'L23', '13', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('г-н Поляков Леон Валентинович', '8306 812104', 'Z88', '7', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Лев Измаилович Туров', '1905 372285', 'V149', '9', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Олимпий Владленович Лазарев', '0320 495876', 'I73', '10', '3')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Аверкий Борисович Трофимов', '2704 558958', 'F124', '9', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ратибор Дмитриевич Киселев', '9502 886335', 'X138', '3', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Тарасов Антип Жанович', '7607 220548', 'Y44', '7', '3')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ольга Сергеевна Соболева', '1812 921953', 'X101', '8', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Светлана Петровна Попова', '5517 206085', 'G99', '7', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Данилов Давыд Ануфриевич', '1001 436855', 'W122', '6', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Федот Трофимович Горбачев', '1015 580832', 'N148', '11', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Владимиров Орест Данилович', '4605 374867', 'H129', '1', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Калинин Федот Бориславович', '7401 038998', 'K61', '8', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Панова Ксения Максимовна', '6309 331131', 'E70', '5', '9')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Красильникова Милица Болеславовна', '0602 130100', 'D96', '15', '9')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Харитонов Нифонт Устинович', '3617 355643', 'E17', '2', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Пестов Аникей Бориславович', '2621 189573', 'S92', '7', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Арефий Анисимович Орехов', '2213 849292', 'Y81', '4', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Прохоров Гордей Брониславович', '3920 884772', 'Y117', '14', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Медведев Антип Гаврилович', '6305 971533', 'B77', '14', '7')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Фотий Дмитриевич Агафонов', '5401 886522', 'O136', '4', '1')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Елена Петровна Семенова', '0211 330401', 'Z22', '2', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Калинина Кира Федоровна', '5210 601667', 'C3', '10', '9')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Эмилия Вячеславовна Белова', '3806 378968', 'E53', '10', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Марина Олеговна Григорьева', '0913 344028', 'J26', '13', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Белозерова Мария Георгиевна', '4211 790504', 'O107', '9', '2')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Ефремова Прасковья Рудольфовна', '1209 840929', 'J2', '2', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Уварова Ольга Никифоровна', '4019 276886', 'K34', '4', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Зайцева Анжела Антоновна', '9108 966222', 'Y44', '11', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Королев Фортунат Арсенович', '9109 091180', 'I11', '2', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Дорофеев Лука Игнатьевич', '8309 115581', 'Q116', '6', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Селезнев Ермолай Эдгарович', '8811 320793', 'V110', '11', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Матвей Феоктистович Вишняков', '8404 426304', 'Q107', '10', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Симонов Александр Ярославович', '8601 336578', 'S132', '1', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Поликарп Ефремович Филатов', '9815 385952', 'T107', '10', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('г-жа Крюкова Анжелика Робертовна', '3207 079676', 'G10', '3', '3')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Прохорова Анжела Валентиновна', '5813 574751', 'L97', '9', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('г-н Цветков Ерофей Валентинович', '1412 886830', 'I72', '2', '2')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Лобанов Эмиль Власович', '7518 713853', 'P148', '10', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('г-жа Селезнева Вероника Степановна', '3812 533492', 'F7', '2', '9')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Татьяна Афанасьевна Зиновьева', '8118 078685', 'J133', '5', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Денис Елизарович Колобов', '9401 007537', 'L134', '12', '2')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Галкин Максимильян Ермилович', '2407 384513', 'A112', '5', '2')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Зосима Бенедиктович Белозеров', '2610 479261', 'R43', '1', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Кондратий Ярославович Власов', '4117 124748', 'G105', '11', '5')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Харитонов Радислав Устинович', '8003 020312', 'W50', '13', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Святослав Валерианович Щукин', '2506 293204', 'N26', '8', '8')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Анжела Ждановна Евдокимова', '1807 180838', 'E53', '5', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Кулакова Прасковья Артемовна', '5114 455856', 'O87', '4', '3')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Фаина Натановна Большакова', '0813 025620', 'K34', '7', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Потапова Оксана Тимофеевна', '5108 285909', 'D106', '4', '6')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Орлова Наина Валериевна', '3714 560782', 'Y60', '9', '4')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Беляева Мария Альбертовна', '3909 400468', 'G34', '12', '2')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Шашков Тихон Абрамович', '7719 312302', 'B69', '6', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Сафонов Леонтий Егорович', '7501 196095', 'L98', '13', '9')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Юдин Ратибор Герасимович', '4713 443629', 'Y76', '8', '10')
INSERT INTO Passenger (passenger_name, passenger_passport, passenger_number, price_id, flight_id) VALUES('Брагин Корнил Игнатович', '7703 255203', 'C106', '7', '10')
