INSERT INTO Timetable (timetable_time) VALUES('Пн-Пт, 7:00-21:00, Сб-Вс, 8:00-22:00')
INSERT INTO Timetable (timetable_time) VALUES('Ежедневно, 9:00-22:00')
INSERT INTO Timetable (timetable_time) VALUES('Ежедневно, 7:00-23:00')
INSERT INTO Timetable (timetable_time) VALUES('Ежедневно, 9:00-21:00')
INSERT INTO Timetable (timetable_time) VALUES('Пн-Пт, 6:00-21:00, Сб-Вс, 8:00-23:00')
INSERT INTO Timetable (timetable_time) VALUES('Ежедневно, 8:00-22:00')
INSERT INTO Discount (discount_amount) VALUES('30')
INSERT INTO Discount (discount_amount) VALUES('20')
INSERT INTO Discount (discount_amount) VALUES('20')
INSERT INTO Discount (discount_amount) VALUES('30')
INSERT INTO Discount (discount_amount) VALUES('30')
INSERT INTO Hall (hall_name, timetable_id) VALUES('Тренажерный зал', '3')
INSERT INTO Hall (hall_name, timetable_id) VALUES('Бассейн', '5')
INSERT INTO Hall (hall_name, timetable_id) VALUES('Спортзал', '4')
INSERT INTO Hall (hall_name, timetable_id) VALUES('Групповой зал', '4')
INSERT INTO Hall (hall_name, timetable_id) VALUES('Детская комната', '3')
INSERT INTO Hall (hall_name, timetable_id) VALUES('Фитнес зал', '1')
INSERT INTO Trainer (trainer_name, trainer_gender, trainer_dob, trainer_passport, trainer_category, trainer_tel, trainer_addr) VALUES('Дьячкова Евфросиния Макаровна', 'Ж', '2008-05-27', '3802 278758', 'тренер второй квалификационной категории', '8 439 513 63 73', 'с. Октябрьское (Челяб.), алл. Лесозаводская, д. 2 к. 136, 058018')
INSERT INTO Trainer (trainer_name, trainer_gender, trainer_dob, trainer_passport, trainer_category, trainer_tel, trainer_addr) VALUES('Пров Феофанович Филатов', 'М', '1926-07-31', '9005 691664', 'тренер высшей квалификационной категории', '8 773 958 3656', 'с. Егорьевск, бул. Калинина, д. 8 к. 14, 629198')
INSERT INTO Trainer (trainer_name, trainer_gender, trainer_dob, trainer_passport, trainer_category, trainer_tel, trainer_addr) VALUES('Ситникова Зоя Егоровна', 'Ж', '1938-03-11', '5907 866902', 'тренер первой квалификационной категории', '81511844282', 'клх Ряжск, пер. Панфилова, д. 90, 108795')
INSERT INTO Trainer (trainer_name, trainer_gender, trainer_dob, trainer_passport, trainer_category, trainer_tel, trainer_addr) VALUES('Шаров Викторин Елисеевич', 'М', '1964-10-29', '4310 551500', 'тренер второй квалификационной категории', '+7 (041) 644-4990', 'г. Соловки, наб. Пархоменко, д. 98 стр. 7/4, 637946')
INSERT INTO Trainer (trainer_name, trainer_gender, trainer_dob, trainer_passport, trainer_category, trainer_tel, trainer_addr) VALUES('Большаков Борис Артёмович', 'М', '1996-09-28', '6406 149408', 'тренер второй квалификационной категории', '87031291729', 'п. Архангельск, бул. Энгельса, д. 41, 958862')
INSERT INTO Service (service_name, service_price, service_dur, hall_id) VALUES('Детская комната', '400', '60', 5)
INSERT INTO Service (service_name, service_price, service_dur, hall_id) VALUES('Тренажерный зал', '300', '60', 1)
INSERT INTO Service (service_name, service_price, service_dur, hall_id) VALUES('Групповые программы', '500', '60', 4)
INSERT INTO Service (service_name, service_price, service_dur, hall_id) VALUES('Детская комната', '500', '90', 5)
INSERT INTO Service (service_name, service_price, service_dur, hall_id) VALUES('Бассейн', '800', '90', 2)
INSERT INTO Service (service_name, service_price, service_dur, hall_id) VALUES('Взрослый фитнес', '400', '90', 6)
INSERT INTO Service (service_name, service_price, service_dur, hall_id) VALUES('Детская комната', '400', '60', 5)
INSERT INTO Service (service_name, service_price, service_dur, hall_id) VALUES('Тренажерный зал', '600', '90', 1)
INSERT INTO Service (service_name, service_price, service_dur, hall_id) VALUES('Бассейн', '600', '90', 2)
INSERT INTO Service (service_name, service_price, service_dur, hall_id) VALUES('Бассейн', '700', '60', 2)
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('2', '1')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('7', '2')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('3', '4')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('4', '4')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('7', '1')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('9', '2')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('1', '2')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('8', '3')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('9', '1')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('9', '4')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('8', '5')
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('7', '3')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Месячный (8 занятий)', '3500', '9')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Годовой (безлимит)', '15000', '4')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Полугодовой (безлимит)', '9000', '4')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Разовый (по выбору)', '800', '8')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Месячный (безлимит)', '5000', '8')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Месячный (4 занятия)', '2000', '1')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Месячный (безлимит)', '5000', '9')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Полугодовой (безлимит)', '9000', '9')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Месячный (4 занятия)', '2000', '3')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Полугодовой (безлимит)', '9000', '8')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Годовой (безлимит)', '15000', '8')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Годовой (безлимит)', '15000', '7')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Годовой (безлимит)', '15000', '4')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Разовый (по выбору)', '800', '10')
INSERT INTO Subscription (subscription_name, subscription_price, service_id) VALUES('Годовой (безлимит)', '15000', '6')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Олимпиада Владиславовна Сафонова', '+76124916305', '2')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Зимина Иванна Юльевна', '+7 193 154 4768', '3')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Агап Гертрудович Петров', '8 (222) 481-90-21', '4')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Поляков Данила Васильевич', '+7 464 581 9073', '2')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Кулагин Лукьян Давидович', '+7 (417) 697-7707', '2')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Герасим Афанасьевич Крюков', '8 286 285 30 05', '2')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Матвеев Тимур Игнатьевич', '8 (761) 924-0611', '3')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Евгений Харламович Фадеев', '8 155 482 30 95', '2')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Тарас Тимурович Максимов', '+7 (012) 437-18-36', '4')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Лонгин Устинович Галкин', '+73391688529', '5')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Блинов Макар Ефимович', '8 447 725 0292', '2')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('г-н Белоусов Аполлон Данилович', '+71404263481', '4')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Николаев Матвей Ефремович', '8 207 965 23 22', '3')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Ладислав Григорьевич Кабанов', '+7 (128) 340-13-23', '5')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('г-н Захаров Станислав Бенедиктович', '+7 (793) 047-81-90', '3')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Ермолай Юлианович Кошелев', '83132485053', '4')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Ольга Захаровна Русакова', '8 (546) 391-19-09', '1')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Анжела Ивановна Шубина', '8 038 236 2122', '3')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Сидорова Регина Кузьминична', '+7 639 946 04 60', '1')
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Архипова Раиса Святославовна', '+77566768631', '5')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('16', '1')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('12', '15')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('19', '4')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('9', '2')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('20', '8')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('16', '8')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('12', '1')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('15', '12')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('1', '13')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('17', '7')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('17', '6')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('16', '9')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('3', '15')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('16', '12')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('19', '13')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('5', '7')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('17', '14')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('14', '1')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('1', '15')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('6', '13')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('17', '8')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('7', '10')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('15', '4')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('10', '4')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('12', '4')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('11', '5')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('12', '8')
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('2', '12')
