INSERT INTO Trainer (trainer_name, trainer_gender, trainer_dob, trainer_passport, trainer_category, trainer_tel, trainer_addr) VALUES('Аким Давидович Власов', 'М', '1916-08-06', '1003 059521', 'тренер высшей квалификационной категории', '+7 756 050 2016', 'п. Артем, алл. Свободы, д. 28 к. 8, 304370');
INSERT INTO Trainer (trainer_name, trainer_gender, trainer_dob, trainer_passport, trainer_category, trainer_tel, trainer_addr) VALUES('Аким Трофимович Мухин', 'М', '1906-01-29', '3206 125421', 'тренер высшей квалификационной категории', '8 (405) 951-1371', 'д. Сортавала, ул. Семашко, д. 93 к. 7/5, 099842');
INSERT INTO Trainer (trainer_name, trainer_gender, trainer_dob, trainer_passport, trainer_category, trainer_tel, trainer_addr) VALUES('Зуев Парфен Гертрудович', 'М', '1974-01-04', '4614 373693', 'тренер высшей квалификационной категории', '+7 (342) 155-95-96', 'с. Кедровый, алл. Баумана, д. 8/9, 901698');
INSERT INTO Trainer (trainer_name, trainer_gender, trainer_dob, trainer_passport, trainer_category, trainer_tel, trainer_addr) VALUES('Шарапов Остап Яковлевич', 'М', '1946-08-21', '9016 132097', 'тренер второй квалификационной категории', '8 (720) 253-94-21', 'клх Бомнак, ул. Лазо, д. 5/6, 296867');
INSERT INTO Trainer (trainer_name, trainer_gender, trainer_dob, trainer_passport, trainer_category, trainer_tel, trainer_addr) VALUES('Фаина Леонидовна Дементьева', 'Ж', '1972-12-07', '8104 080298', 'тренер высшей квалификационной категории', '+79802870023', 'д. Чокурдах, бул. Украинский, д. 8 стр. 850, 343723');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('4', '2');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('10', '1');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('3', '4');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('6', '1');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('1', '4');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('8', '4');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('12', '2');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('3', '3');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('11', '3');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('5', '1');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('9', '3');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('9', '4');
INSERT INTO Service_trainer (service_id, trainer_id) VALUES('10', '3');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Давыд Феофанович Владимиров', '8 378 223 9995', '4');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Филиппов Валерьян Владиленович', '+7 (224) 017-2620', '4');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Афанасьев Евграф Устинович', '8 257 870 8992', '1');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Парамон Власович Васильев', '+7 (698) 444-21-32', '1');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Кириллова Вера Евгеньевна', '+7 985 615 3363', '3');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Баранова Валентина Евгеньевна', '+74619582488', '4');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('София Вадимовна Фадеева', '+7 438 963 97 87', '1');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Елизавета Эльдаровна Гусева', '86995086283', '4');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Чернова Феврония Геннадиевна', '8 341 259 4805', '2');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Алла Кузьминична Назарова', '8 976 219 09 77', '2');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Елисеев Тит Гурьевич', '8 (687) 770-69-65', '2');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Куликов Артемий Давидович', '8 743 831 54 18', '4');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Пелагея Болеславовна Горшкова', '+71596841533', '1');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Кузнецова Елена Леонидовна', '8 543 602 7873', '4');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Наина Геннадьевна Филиппова', '8 (218) 129-40-36', '1');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Ия Наумовна Жукова', '+7 (204) 571-14-38', '2');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Авдей Виленович Давыдов', '8 (785) 905-54-30', '4');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Орест Эдгарович Аксенов', '+7 997 464 9734', '3');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Ираида Викторовна Агафонова', '+7 418 094 8317', '2');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Веселова Нинель Сергеевна', '8 518 073 31 16', '1');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Абрамова Жанна Геннадиевна', '+7 (384) 793-35-55', '2');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Селезнева Лукия Геннадьевна', '+7 (839) 260-1200', '1');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Алина Сергеевна Комарова', '8 (865) 794-4847', '1');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Анисимова Олимпиада Альбертовна', '+7 294 080 5728', '2');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Гришин Федосий Устинович', '+7 267 284 42 23', '4');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Самойлов Твердислав Андреевич', '+7 781 998 4729', '2');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Творимир Ануфриевич Цветков', '+7 704 593 9569', '1');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Мясников Наум Гавриилович', '8 (223) 759-56-23', '3');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Элеонора Ильинична Маслова', '84319493826', '2');
INSERT INTO Customer (customer_name, customer_tel, discount_id) VALUES('Морозова Анжела Леонидовна', '82598220005', '1');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('22', '4');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('28', '6');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('14', '6');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('20', '4');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('17', '3');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('29', '5');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('19', '6');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('22', '2');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('19', '5');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('28', '5');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('19', '4');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('3', '6');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('12', '5');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('1', '6');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('29', '2');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('16', '1');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('8', '5');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('4', '5');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('23', '2');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('24', '4');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('6', '5');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('20', '2');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('14', '5');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('7', '5');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('10', '2');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('17', '2');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('1', '4');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('19', '2');
INSERT INTO Customer_subscription (customer_id, subscription_id) VALUES('8', '3');
